### ISSUE TITLE
Rate-based Data Source

### ISSUE THREAD

**Issue by finger563** [krpc/krpc#116]
An additional feature to allow for configuring rate-based publishing of sensor data (e.g. position, velocity, etc.).  This could be done through broadcast or multiple unicast transmissions.

**Comment by djungelorm** [comment]
This is already possible using "streams", although the rate is not configurable, and they are poorly documented... They are used in this tutorial to subscribe to telemetry data from the vessel: http://djungelorm.github.io/krpc/docs/tutorials/launch-into-orbit.html

Here's an example of how you could use streams to get data from a sensor:
```python
import krpc
conn = krpc.connect()
sensors = conn.space_center.active_vessel.parts.sensors
sensor = sensors[0]
value = conn.add_stream(getattr, sensor, 'value')
while True:
    print value()
    time.sleep(1)
```
The line ```print value()``` doesn't actually run an RPC, it just gets the last value that the client received from the server.

Does this match your requirements?

**Comment by finger563** [comment]
Ah yes, I figured this was what streams were useful for, but hadn't found much relevant documentation for setting them up.  Thanks for the pointer to the code, i'll start using it in my code.  I've been developing a c++ library (it's in early stages) for use with KRPC (and ROS) for which this will be quite useful.  Is this only useful for sensors, or can I, for instance, have it output vessel position/velocity/orientation/etc. ?  If it can handle those data, it should suffice for now, and I might play around with your code to see about getting rate modifications to work.  Thanks for the responses, by the way;  I'm hoping that the combination of this + my (and my colleagues) work will make for a useful tool in both ours and others' research :)

**Comment by djungelorm** [comment]
You can set up a stream for any RPC. Instead of calling the RPC directly, you pass the function and it's arguments to conn.add_stream. So yes, you can use this to repeatedly fetch a vessel's velocity.

Some examples:
```python
# for a method - calls vessel.velocity(vessel.orbit.body.reference_frame)
v = conn.add_stream(vessel.velocity, vessel.orbit.body.reference_frame)

# for a property - calls vessel.situation
situation = conn.add_stream(getattr, vessel, 'situation')
```

**Comment by djungelorm** [comment]
The bit of code that does the stream updates is here: https://github.com/djungelorm/krpc/blob/master/src/kRPC/KRPCServer.cs#L220
It's invoked every time Unity triggers a physics update (fixed update).

**Comment by finger563** [comment]
Ah ok thanks!  I'll take a look at that.  What I was planning on doing was having a thread-pool of workers which handle tasks invoked by different clients (we want multiple (at least 32) clients connected to one or more copies of KSP) which have sets of tasks, some of which may need to be invoked at different rates.  Conversely I can possibly put this into my client-side library.

**Comment by finger563** [comment]
Should the rate-based publishing of stream data be coupled with the move to a multi-threaded approach?  I imagine this would help for performance with many clients as well as ensuring proper rates for each stream.  Interested to hear your thoughts on this.

**Comment by djungelorm** [comment]
Regarding multi-threading, we'll have to see what happens when KSP moves to Unity 5, as at the moment using threads would be a bit of a nightmare as I highly doubt the KSP API is thread safe!

In the meantime, we should be able to implement something that approximates rate control per-stream. For example, by occasionally skipping updating a stream from FixedUpdate, we can reduce the rate from the current fixed rate that FixedUpdate runs at. Assuming FixedUpdate runs at 60FPS, we can provide streams with rates of 30FPs, 15FPS, and other multiples by just choosing a number of updates to skip. Although this wouldn't provide the precise rate that is requested, it'd be a start. And this should be trivial to implement.

**Comment by djungelorm** [comment]
#141
