### ISSUE TITLE
Support for other transports - websocket

### ISSUE THREAD

**Issue by goncalopp** [krpc/krpc#130]
First of all, thank you for a fantastic project, and a clean and documented API!

I noticed you mentioned supporting other communication protocols in the future. This would enable a lot of new use cases - especially for web clients, [as has happened with Telemachus](https://github.com/richardbunt/Telemachus/wiki/Alternative-Telemachus-Interfaces).

You mentioned SOAP on your post, but I think Websocket has some important advantages:

 - much simpler
 - more efficient (a *lot* less request/response overhead)
 - support for binary messages out-of-the-box (thus wrapping protobuf over it is trivial)

There are several options for using protobufs in javascript. [ProtoBuf.js](https://github.com/dcodeIO/ProtoBuf.js) is probably a good choice

**Comment by djungelorm** [comment]
I don't really know about SOAP/websockets but at quick glance at the wikipedia page for SOAP did look rather heavyweight. So thanks for the pointer!

There's already a ticket for this stuff here: #123

**Comment by djungelorm** [comment]
Closing, as this is being discussed over on that other issue.
