### ISSUE TITLE
Mark procedures, whose return value depends only on "this" parameter.

### ISSUE THREAD

**Issue by TeWu** [krpc/krpc#171]
If procedures, whose return value depends only on "this" parameter (like `Vessel.control`), are marked (probably by attribute), then client libraries could use that information for optimization. Those procedures are usually called via parameterless methods in some objects. If those procedures ware marked, then theirs return value could be cached in the object's instance variable(s).

**Comment by djungelorm** [comment]
This would add additional complexity to the service API, server API and all the clients for the various languages. I would prefer to leave the script writer to cache the value themselves if they really need the performance. When running with a connection on localhost, in my experience the over head is not too large.

The use case here is that things like the following could be made faster:
```
while True:
    vessel.control.pitch = ...
   ...
```

However, to get better performance, it is not too painful to have to write:
```
c = vessel.control
while True:
    c.pitch = ...
   ...
```

**Comment by TeWu** [comment]
I think this can be closed:

1. Attributes have been removed in v0.4.0
2. If client is using `GetServices` to get info about procedures, then it can use [`parameters`][1] field from from `Procedure` protobuf message to determine whether return value depends only on "this" parameter - no need for any additional marking.

[1]: https://github.com/krpc/krpc/blob/7f9265f9cf259afc0947c083c343bd8c9edc439d/protobuf/krpc.proto#L49
