### ISSUE TITLE
KSP 1.0.5 thermal changes

### ISSUE THREAD

**Issue by djungelorm** [krpc/krpc#174]

**Comment by djungelorm** [comment]
0.1.12 is built for 1.0.5 but does not include any thermal changes etc. These need to be included in 0.1.13.

**Comment by artwhaley** [comment]
Which changes need to be updated for?  This sounds like the sort of small task I can help with?

**Comment by djungelorm** [comment]
I think there were changes to the thermal system, so some of the SpaceCenter API may now be wrong, or there may be new features missing. I've not looked into this yet. If you could take a look that'd be great! Thanks :)

**Comment by djungelorm** [comment]
Whilst fixing up the space center tests I found that Part.ExternalTemperature throws a not implemented exception.

It used to call part.skinUnexposedExternalTemp but this property was removed in KSP 1.0.5. We need to investigate if we should just remove this property or if it has been renamed.

**Comment by djungelorm** [comment]
Found a bunch of info on the heat model here: http://forum.kerbalspaceprogram.com/index.php?/topic/113772-part-heating-rate/

**Comment by djungelorm** [comment]
I've removed Part.ExternalTemperature, and updated the thermal mass and flux methods so that they return values in SI units.

I don't think the properties provided covers the entirety of KSPs thermal model, but what is there should suffice for now.
