### ISSUE TITLE
invalid surface_velocity_reference_frame 

### ISSUE THREAD

**Issue by Assert1** [krpc/krpc#194]
vessel.velocity and flight.velocity with surface_velocity_reference_frame in my environment throws an exception all the time with _error "forward and up directions are not close to perpendicular"

                case Type.VesselSurface:
                    {
                        var right = vessel.GetWorldPos3D () - vessel.mainBody.position;
                        return Vector3d.Exclude (right, ToNorthPole (vessel).normalized);
                    }

                case Type.VesselSurface:
                    {
                        var right = vessel.GetWorldPos3D () - vessel.mainBody.position;
                        var northPole = ToNorthPole (vessel).normalized;
                        return Vector3d.Cross (right, northPole);
                    }

looks like UpNotNormalized and ForwardNotNormalized are collinear, no?

**Comment by djungelorm** [comment]
I'm having trouble reproducing the issue.

I tried the following, while flying an aircraft:
```python
import krpc
conn = krpc.connect(address="10.0.2.2")

vessel = conn.space_center.active_vessel

print vessel.velocity(vessel.surface_velocity_reference_frame)
print vessel.flight(vessel.surface_velocity_reference_frame).velocity
```

From which I got:
```python
(0.0, -0.0, 0.0)
(0.0, -0.0, 0.0)
```
Which is the expected, as the reference frame is fixed relative to the vessel.

Can you provide some more details on how I can reproduce this bug?

That code looks right to me. The first bit of code returns the cross product of X and Y (which is a vector perpendicular to the plane of X and Y), and the second bit returns X with it's component in the Y direction removed (which is in the plane of X and Y).

**Comment by Assert1** [comment]
I made some investigation. Exception is not thrown while vessel in prelaunch state, so you need to launch your vessel to reproduce. I used this C++ code for test:

void main()
{
	auto client=krpc::connect("Example");
	krpc::services::KRPC krpc(&client);	
	krpc::services::SpaceCenter sc(&client);
	auto vessel=sc.active_vessel();
	auto fs=vessel.flight(vessel.surface_velocity_reference_frame());
	while(fs.mean_altitude()<1000)
	{
		auto vel=fs.velocity();
		printf("%.2f, %.2f %.2f\n", boost::get<0>(vel), boost::get<1>(vel), boost::get<2>(vel));
	};
};
Run this, then launch the vessel. So exception is thrown as soon as engines are active. Also, the Realism Overhaul mod is installed in my environment, and launch pad is near an equator (may be this have some meaning).

**Comment by Assert1** [comment]
surface_reference_frame also incorrect, always returns (0.0, 0.0, 0.0)

**Comment by djungelorm** [comment]
I installed realism overhaul (using CKAN) and ran your example script but don't see the error :( I just get 0,0,0 printed out continuously until the vessel reaches 1000m altitude.

The craft I used was just a Mk1 pod attached to an SRB. Maybe it is something to do with the specific craft you used? Would you be able to send me a .craft file?

Also could you send a list of the mods and versions that you use so I can reproduce your environment? If you're using CKAN you can just go File -> Export mods to get a .ckan file with a list of them all.

**Comment by Assert1** [comment]
Sorry, was alot of work...

Mk1 Pod + Castor 30XL booster
Launch site: US - Cape Canaveral

[current_mods..ckan.txt](https://github.com/krpc/krpc/files/148833/current_mods.ckan.txt)
video: http://www.4shared.com/video/oQ72_x9Kba/bandicam_2016-02-27_00-59-40-4.html

May be this is floating point precision feature/bug of AMD processor?

**Comment by djungelorm** [comment]
Thanks! I'll have another go at reproducing it.

**Comment by djungelorm** [comment]
Real Solar System is the culprit. I get the error with just that mod (and its dependencies) installed. And yes, I think it is float point precision/overflow related. I added some print statments to the krpc code where it computes the reference frame and got this:

```
vessel pos = [-0.116741026751697, -0.0209901100024581, -0.0178471594117582]
body pos = [-5269714.39625549, -3050614.70720863, -1874787.29597473]
velocity = [-0.484183798222915, -0.282226294279099, -0.172867009485913]
proj = [19690618468680.2, 11398813426145.8, 7005260445912.97]
result = [0, 8192, -8192]
```

The numbers in the proj vector are rather huge...

**Comment by djungelorm** [comment]
I forgot to normalize a vector in one of the calculations... oops! Here's a patched copy of KRPC.SpaceCenter.dll Could you drop it into your GameData/kRPC folder and check that it fixes the issue?
[SpaceCenter.zip](https://github.com/krpc/krpc/files/149218/SpaceCenter.zip)
