### ISSUE TITLE
C#-Client: Can not get vessel velocity

### ISSUE THREAD

**Issue by HukehrsEngineering** [krpc/krpc#215]
C#-Client 0.2.2
Server 0.2.2
KSP 1.0.5
Target .net 4.5

Hey there,

I can not get any kind of surface velocity for my vessel, neither from a single RPC-Call nor from a stream.

Things I've tried:
`_connection.SpaceCenter().ActiveVessel.Flight().Velocity` => (0, 0, 0)
```
var vessel = _connection.SpaceCenter().ActiveVessel;
var refframe = vessel.SurfaceReferenceFrame;
_connection.AddStream<Tuple<double, double, double>>(() => vessel.Velocity(refframe)
``` 
=> (0, 0, 0)
`_connection.SpaceCenter().ActiveVessel.Flight().VerticalSpeed` => 0
`_connection.SpaceCenter().ActiveVessel.Flight().HorizontalSpeed` =>0

In every case the vessel was actually moving a couple of meters per second.

Is there anything I am missing?
Thanks for all your effort.

**Comment by djungelorm** [comment]
A common issue! All of those examples use a reference frame that is fixed relative to the vessel. So the speed is zero.

You probably want to use a reference frame that is fixed relative to kerbin. Examples can be found here: 
http://krpc.github.io/krpc/tutorials/reference-frames.html#orbital-speed

There is also a guide to reference frames here:
http://krpc.github.io/krpc/tutorials/reference-frames.html

**Comment by HukehrsEngineering** [comment]
Thanks. That helps alot.

Maybe it would be helpful to better hint at this in the docs for Flight(), as calling the method without a parameter and getting 0 as result for any speed is rather counter-intuitive.

Should I mark this issue as closed or do you want to leave it open for tracking changes to the documentation?

**Comment by djungelorm** [comment]
Yep good plan. Leave it open for now.

**Comment by djungelorm** [comment]
I've added a "note" to Vessel.Flight: http://krpc.github.io/krpc/csharp/api/space-center/vessel.html#method-Vessel.Flight

Does that make it clearer?

**Comment by HukehrsEngineering** [comment]
Yes. This explains it very well!
