### ISSUE TITLE
RotationRateController issues

### ISSUE THREAD

**Issue by chippydip** [krpc/krpc#233]
1) RotationRateController passes the setpoint (target angular velocity) to the PID controller when it should be passing the input (current angular velocity). This makes Kd worse than worthless--instead of helping to damp out oscillations it will effectively just provide a negative derivative kick, making the controller slower to respond to new commands.

2) RotationRateController isn't reset when AutoPilot is engaged so integral and derivative terms will be using old values. This will only be an issue for one tick with the derivative term, and could be avoided by setting Kd to 0 for at least one tick to ignore this term. The integral term, on the other hand, is pre-multiplied as it accumulates so even setting Ki to 0 won't prevent it from impacting the controller's output (and it's value will persist for quite a while).

2) The way the PIDController handles clamping causes steering issues if RotationRateController ever tries to drive it past the -1 to 1 limits. If a slow-turning rocket accumulates enough of an integral term or the proportional term is increased enough you can end up in a situation where the raw controller output would be +2 pitch and +0.5 yaw, which is clamped to +1 pitch and +0.5 yaw. This ends up changing the actual steering direction so instead of moving straight toward the target the controller will end up spiraling toward it as the controller slowly adjusts to the error in steering direction.

**Comment by djungelorm** [comment]
Thanks for the feedback. The current autopilot is indeed a horrific mess and needs to be completely rewritten. I wrote it with a rather terrible understanding of control theory...

As a first step to a better autopilot, we're currently adding RPCs for computing things like moment of inertia and torque (from gimballed engines/rcs/reaction wheels and aero surfaces) Details here: #212 
Once that's done I'm going to play around with writing a better autopilot, initially as a python script (which will allow for faster prototyping) and then port it into kRPC to replace the current autopilot.

**Comment by djungelorm** [comment]
Here's an update on my progress at re-implementing the autopilot in case you're interested: http://forum.kerbalspaceprogram.com/index.php?/topic/62902-105-krpc-remote-procedure-call-server-v022-28th-feb-2016/&do=findComment&comment=2460919

**Comment by chippydip** [comment]
Cool, I'll play around with it this weekend.

**Comment by djungelorm** [comment]
The new autopilot has been released in 0.3.5. Should fix these issues.
