### ISSUE TITLE
Is there any way to determine the current game scene?

### ISSUE THREAD

**Issue by FenixFeather** [krpc/krpc#237]
I want to make a script that does stuff on game scene change. Is it possible to do this without needing to extend krpc?

**Comment by FenixFeather** [comment]
Okay, a kind of hacky way to do it is to run ```conn.space_center.active_vessel``` and examine the exception text...

**Comment by djungelorm** [comment]
Yeah thats one way of doing it! I'll add an RPC to access this directly.

**Comment by FenixFeather** [comment]
Yay! I've already implemented a [custom soundtrack player](https://github.com/FenixFeather/ksp-music-hack) using your mod. Awesome mod!

**Comment by djungelorm** [comment]
0.2.3 has been released, which includes the new RPC. The documentation for it is here: http://krpc.github.io/krpc/python/api/krpc.html#KRPC.current_game_scene

For example:
```
conn = krpc.connect()
print conn.krpc.current_game_scene
```
