### ISSUE TITLE
Keep the Java client JDK 1.7 compatible

### ISSUE THREAD

**Issue by evanova** [krpc/krpc#242]
**Use Case**: I want to be able to use the Java JAR client file with JDK 1.7 without having to rebuild it.

**Issue**: it appears that the Java client JAR is built with JDK 1.8. This prevents using KRPC in environments that only allow JDK 1.7. In particular, I want to build an Android client but the current build will not work since Android is JDK 1.7

**Fix**: remove the call to String.join() from **Connection.java** and build using a target JDK to 1.7

To fix it, I created a Ubuntu VM and built a custom JAR files with directions from https://krpc.github.io/krpc/compiling.html while making sure I am using JDK 1.7.

**Comment by djungelorm** [comment]
This should now be resolved. The changes also allow us to build a JDK 1.7 compatible JAR with Bazel running with either JDK 1.7 or 1.8.

Thanks!
