### ISSUE TITLE
Export the rigidbody field of vessel parts?

### ISSUE THREAD

**Issue by ikirill** [krpc/krpc#249]
It would be nice to export the rigidbody field of vessel parts, because it seems impossible to get the correct moments of inertia for the vessel without knowing the moments of inertia for the constituent parts. Using only the mass and positions of parts is not sufficient. For example, here's MechJeb2: https://github.com/MuMech/MechJeb2/blob/82b9a3ab4d98f8248d6bf3d5827e8436fd2414b7/MechJeb2/VesselState.cs#L927

Looking at mechjeb, each part has a field `Rigidbody`, and each rigid body has `inertiaTensor` and `inertiaTensorRotation`.

There is an identical omission in KOS too: https://github.com/KSP-KOS/KOS/issues/690

**Comment by djungelorm** [comment]
Already on its way in #212 :) There's a list of the new rpcs on that issue. Let me know if there are any others you think should be added.

**Comment by ikirill** [comment]
Thanks! I didn't see that issue/branch.

**Comment by ikirill** [comment]
I'm unable to build the `autopilot-rpcs` branch (or `krpc` itself) on OSX, but I'm not sure if that's a bug or you just don't support building on OSX.

**Comment by djungelorm** [comment]
I've not tried that before, and don't have access to an OSX machine. If Bazel works on OSX then it should be possible.

I've made an issue to discuss this here: #250

**Comment by djungelorm** [comment]
And no, I'm afraid there's no way to pause an RPC until the next frame. What's the use case for needing this?

**Comment by ikirill** [comment]
If you have a loop that continuously prints something, 

    while True: print KSP.space_center.active_vessel.control.pitch

then IIUC it may print identical data from the same frame multiple times. If I use something like `time.sleep(0.001)`, then it's not totally clear how many frames (although probably 1) have elapsed between consecutive RPCs.
