### ISSUE TITLE
Building on OSX

### ISSUE THREAD

**Issue by djungelorm** [krpc/krpc#250]

**Comment by ikirill** [comment]
I get the following errors on OSX (apart from some earlier ones that were easier to solve), with KSP 1.1-pre:

```
krpc $ bazel build //server //client/python
INFO: Found 2 targets...
ERROR: /Users/kirill/Sandboxes/Games/KerbalSpaceProgram/krpc/tools/build/ksp/BUILD:18:1: error executing shell command: 'ln -f -r -s external/csharp_protobuf_net35/file/Google.Protobuf.dll bazel-out/local_darwin-fastbuild/bin/tools/build/ksp/Google.Protobuf.dll' failed: bash failed: error executing command /bin/bash -c 'ln -f -r -s external/csharp_protobuf_net35/file/Google.Protobuf.dll bazel-out/local_darwin-fastbuild/bin/tools/build/ksp/Google.Protobuf.dll': com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
ln: illegal option -- r
usage: ln [-Ffhinsv] source_file [target_file]
       ln [-Ffhinsv] source_file ... target_dir
       link source_file target_file
ERROR: missing input file '//lib:ksp/KSP_Data/Managed/TDx.TDxInput.dll'.
ERROR: /Users/kirill/Sandboxes/Games/KerbalSpaceProgram/krpc/tools/build/ksp/BUILD:9:1: //tools/build/ksp:TDx.TDxInput: missing input file '//lib:ksp/KSP_Data/Managed/TDx.TDxInput.dll'.
ERROR: /Users/kirill/Sandboxes/Games/KerbalSpaceProgram/krpc/tools/build/ksp/BUILD:9:1 1 input file(s) do not exist.
INFO: Elapsed time: 0.251s, Critical Path: 0.06s
```

The file `TDx.TDxInput.dll` doesn't exist in the Managed directory of my KSP install from Steam on OSX:
```
krpc $ find ../KSP/KSP.app -name "*.dll"
../KSP/KSP.app/Contents/Data/Managed/Assembly-CSharp.dll
../KSP/KSP.app/Contents/Resources/Data/Managed/Assembly-CSharp-firstpass.dll
../KSP/KSP.app/Contents/Resources/Data/Managed/Assembly-CSharp.dll
../KSP/KSP.app/Contents/Resources/Data/Managed/Assembly-UnityScript-firstpass.dll
../KSP/KSP.app/Contents/Resources/Data/Managed/Assembly-UnityScript.dll
../KSP/KSP.app/Contents/Resources/Data/Managed/Boo.Lang.dll
../KSP/KSP.app/Contents/Resources/Data/Managed/KSPAssets.dll
../KSP/KSP.app/Contents/Resources/Data/Managed/KSPCore.dll
../KSP/KSP.app/Contents/Resources/Data/Managed/KSPUtil.dll
../KSP/KSP.app/Contents/Resources/Data/Managed/MiscUtil-r285.dll
../KSP/KSP.app/Contents/Resources/Data/Managed/Mono.Cecil.dll
../KSP/KSP.app/Contents/Resources/Data/Managed/Mono.Security.dll
../KSP/KSP.app/Contents/Resources/Data/Managed/mscorlib.dll
../KSP/KSP.app/Contents/Resources/Data/Managed/SaveUpgradePipeline.Core.dll
../KSP/KSP.app/Contents/Resources/Data/Managed/System.Core.dll
../KSP/KSP.app/Contents/Resources/Data/Managed/System.dll
../KSP/KSP.app/Contents/Resources/Data/Managed/System.Xml.dll
../KSP/KSP.app/Contents/Resources/Data/Managed/System.Xml.Linq.dll
../KSP/KSP.app/Contents/Resources/Data/Managed/TrackIRUnity.dll
../KSP/KSP.app/Contents/Resources/Data/Managed/UnityEngine.dll
../KSP/KSP.app/Contents/Resources/Data/Managed/UnityEngine.Networking.dll
../KSP/KSP.app/Contents/Resources/Data/Managed/UnityEngine.UI.dll
../KSP/KSP.app/Contents/Resources/Data/Managed/UnityScript.Lang.dll
../KSP/KSP.app/Contents/Resources/Data/Managed/Vectrosity.dll
../KSP/KSP.app/Contents/Resources/Data/Managed/xmldiffpatch.dll
../KSP/KSP.app/Contents/Resources/Data/Managed/XmlDiffPatch.View.dll
```

and `ln` doesn't have a `-r` option on OSX.

**Comment by djungelorm** [comment]
The `-r` option was added to `ln` in GNU's coreutils package in version 8.16. Is it possible to update the version on OSX?

**Comment by djungelorm** [comment]
Looks like the TDx dll isn't needed... Here's a patch to remove all reference to it from the build scripts which should fix that issue: https://gist.github.com/djungelorm/0d3edc9c2837bc1ad563327450d66a87

**Comment by ikirill** [comment]
OSX doesn't use coreutils and comes with its own ln, and it seems unreasonable to replace the system `ln` with another `ln`. I installed coreutils separately, but bazel doesn't seem to keep the environment $PATH variable, so ignores it anyway. I have the same issue with rsvg-convert missing from $PATH too.

Do you know how to add something to $PATH in bazel? Quick search gave me nothing.

**Comment by djungelorm** [comment]
Bazel doesn't observe the `$PATH` variable. It's one of the ways they enforce reproducible builds. On Linux, Bazel will only run tools located in `/bin`. It sandboxes all it's build actions, so that they can only access files in certain locations. On OSX, I don't think Bazel currently does sandboxing, so maybe try putting `ln` in `/usr/local/bin` or one of the other default locations as a workaround?

I think the best solution might be to remove the use of `-r` from the build scripts. I'll have a look into doing this.

**Comment by djungelorm** [comment]
Here's another patch, which removes the need for `ln -r`. I tried it on Ubunut 12.04 (which has a very old version of coreutils and it seems to work). https://gist.github.com/djungelorm/a880dbf2851f65aa51e4938f271d0074

**Comment by ikirill** [comment]
That works, thank you.

**Comment by djungelorm** [comment]
Cool! I've also noticed that Travis CI has an OSX build environment, so I'll see if we can get the tests running on there.
