### ISSUE TITLE
More drawing tools

### ISSUE THREAD

**Issue by djungelorm** [krpc/krpc#253]
Move the basic drawing tools provided in `SpaceCenter` to a new service called `Drawing` and add a service called `UI`

Drawing service draws the following in the 3D scene. As a starting point, add support for:
* [x] Line segments
* [x] Polygons (a list of vertices)
* [x] Text meshes

UI services draws and allows interaction with Unity UI elements. As a starting point, add support for:
 * [x] `ScreenMessages.PostScreenMessage`
 * [x] Panels
 * [x] Text labels (KER style)
 * [x] Input fields
 * [x] Buttons

Drawing/UI primitives should be returned as an object, so that the code can modify them. This will avoid the issues of the current approach which requires you to call `ClearDrawing` and redraw everything, causing flickering in game.

**Comment by mdfntr** [comment]
One feature that I feel is missing from kRPC is the ability to print text on the screen in the game. In my use of kRPC, it would save me the pain of switching from full-screen KSP to a terminal window to watch for log messages.

kOS implements the `HUDTEXT` function (https://github.com/KSP-KOS/KOS/blob/develop/src/kOS/Function/Misc.cs#L42) that leverages KSP's own text-displaying functions. Perhaps something similar could be added along with drawing functionality?

**Comment by djungelorm** [comment]
Looks like an almost trivial addition, thanks for the suggestion. I've added it to the list on the opening comment.

**Comment by djungelorm** [comment]
Quick update: I've got the line, polygon and text mesh rendering working nicely. Currently working on creating arbitrary Unity UI elements, so that you will be able to instantiate text at arbitrarily positions on the sceen. Will allow you to do things similar to Kerbal Engineer Redux's HUD text.

**Comment by jwvanderbeck** [comment]
> Will allow you to do things similar to Kerbal Engineer Redux's HUD text.

I absolutely love KERs flight HUDs and the ability to essentially make the same thing with my kRPC data will be golden!

**Comment by jwvanderbeck** [comment]
Having some trouble making this work.  Not sure what I am doing wrong?

```
>>> connection = krpc.connect(name = "HUD", address="10.0.1.10", rpc_port=50000, stream_port=50001)
>>> vessel = connection.space_center.active_vessel
>>> t = connection.drawing.add_text("This is Text", vessel.reference_frame, (0,0,0), (0,0,0), True)
```

The add_text method never completes.  It just hangs there.

**Comment by djungelorm** [comment]
OK, will try and reproduce. A bit busy at the moment though, so won't have time a look at this until later in the week.

**Comment by jwvanderbeck** [comment]
Oh ok, I thought I was just doing it wrong :)

**Comment by djungelorm** [comment]
Looking at your code it looks ok. And a hang suggests a bug. It should at least terminate and give you an error if there is something wrong.

**Comment by djungelorm** [comment]
@jwvanderbeck Just tried running your code, and I see the same behavior. However, I noticed that for the rotation parameter you put (0,0,0) but you need to provide a 4-tuple as it's a quaternion. You can use (0,0,0,1) to mean no rotation. I.e.: ```t = connection.drawing.add_text("This is Text", vessel.reference_frame, (0,0,0), (0,0,0,1), True)```

I'll investigate why it hangs with a 3-tuple and get it to report a more useful error in future...

**Comment by jwvanderbeck** [comment]
Doh, my bad.  I must have had lazy eyeballs.

**Comment by jwvanderbeck** [comment]
Excellent.  Everything seems to work well.

This text is drawn in 3d space, which is cool and useful, but it is also useful to be able to draw text flat on the UI layer.  Is this functionality in here and I just missed it, or is that not yet available?
