### ISSUE TITLE
Python: "Unknown game scene" when accessing current_game_scene in VAB/SPH

### ISSUE THREAD

**Issue by Lokaltog** [krpc/krpc#262]
I'm playing around with the Python API (0.3.0) connecting to kRPC 0.3.0 on KSP 1.1 (Linux x64). I'm planning on creating a display that shows vessel and part properties while building, but when running a simple test script I receive an error when I'm inside the VAB or SPH, instead of receiving a `editor_vab` or `editor_sph` game scene. Other scenes like the tracking station or space center properly return a `GameScene`.

```python
conn = krpc.connect(name='Test')
scene = conn.krpc.current_game_scene
```

```
Traceback (most recent call last):
  File "...", line 8, in <module>
    scene = conn.krpc.current_game_scene
  File "<string>", line 1, in <lambda>
  File ".../venv/lib/python3.5/site-packages/krpc/client.py", line 84, in _invoke
    raise RPCError(response.error)
krpc.error.RPCError: Unknown game scene
```

Is this feature not implemented yet, or could it be a bug related to the 1.1 release? I apologize if this is a known issue, I tried searching the issue tracker but couldn't find anything related to this error message.

**Comment by djungelorm** [comment]
This is indeed a bug. Also, the SpaceCenter API is currently only available when in the flight scene, so you won't be able to access it from the editor. I've added a separate issue to add that feature: #263
