### ISSUE TITLE
Gimbal Angle Reference Frame

### ISSUE THREAD

**Issue by mdfntr** [krpc/krpc#267]
In [the documentation](https://krpc.github.io/krpc/python/api/space-center/parts.html#SpaceCenter.Thruster.gimbal_angle), the `gimbal_angle` property is stated to return the current angle in the pitch, roll, and yaw axes. What reference frame are these values measured in? Is the angle from the gimbal position or from the vehicle's center of mass?

How would you suggest to obtain appropriate vectors for force and position of a gimballed thruster in order to calculate that thruster's current and maximum torque through the center of mass?

**Comment by djungelorm** [comment]
The pitch/roll/yaw axes correspond to the reference frame ```vessel.reference_frame``` and the rotation is centered on the position of the gimbal. (Internally, the value returned is just ```ModuleGimbal.actuation```)

If you just want the current available torque, I'm working on some changes to add an AvailableTorque property to the ReactionWheel, Engine, RCS and ControlSurface objects, which returns the torque in the pitch/roll/yaw axes. I will hopefully release v0.3.3 with these changes sometime on Sunday, but if you want to try them out now you can download a pre-release build from here: https://krpc.s3.amazonaws.com/deploy/feature/autopilot-rpcs/413.1/krpc-0.3.2-8-g73c3f33.zip

**Comment by mdfntr** [comment]
Thanks for the response. I apologize if I came across as a bit rude in my question earlier...I was starting to get frustrated with my code and it was coming across in my writing here.

An AvailableTorque property would be amazing! That is effectively what I was trying to calculate out myself. I think I got reasonable values for reaction wheels and RCS thrusters, but gimballed engines were starting to tax my vector visualization abilities. I also hadn't even thought about including control surfaces...good for you for figuring this out.

Thanks for you hard work on this project.

**Comment by djungelorm** [comment]
No need to apologize! :) I'm doing some testing of the available torque stuff now. I was dreading having to calculate this stuff myself - gets a bit complicated especially with engines with multiple nozzles like the SABRE, and if they aren't in line with the center of mass... Fortunately they added "GetPotentialTorque" methods to the KSP API in 1.1 that computes all this for us!

**Comment by djungelorm** [comment]
FYI, I've release v0.3.3 with the available torque properties: http://krpc.github.io/krpc/python/api/space-center/vessel.html#SpaceCenter.Vessel.available_torque
Also ```vessel.moment_of_inertia``` was broken, but should work now. Let me know if you have any issues!
