### ISSUE TITLE
Google Protocol Buffers C# 3.0.0-beta3

### ISSUE THREAD

**Issue by BevoLJ** [krpc/krpc#270]
just a heads up on an update...
https://www.nuget.org/packages/Google.Protobuf/3.0.0-beta3

The beta 2 is linked at the bottom of the beta 3 page if anyone is looking for it. =)

**Comment by BevoLJ** [comment]
Oh, BTW... just wanted to mention real quick that the link in the documentation for the C# KRPC.Client is broken. It currently goes to .../KRPC.Client rather than .../KRPC.Client/0.3.3-pre

**Comment by djungelorm** [comment]
Thanks for the update :)

**Comment by djungelorm** [comment]
The link intermittently works for me... weird. I think it might actually be an issue at nuget. They also use the same link on their site in some places.

**Comment by BevoLJ** [comment]
Hmm, I've never actually gotten it to work.  =P  I just use Google.  It takes me to https://www.nuget.org/packages/KRPC.Client/0.3.3-pre.  =)

**Comment by djungelorm** [comment]
Did some more testing, and turns out if you use http:// instead of https:// it works fine! I've updated the link on the docs site. a564651b2dc29e6c71e4fb4f141472c085e1fb13
