### ISSUE TITLE
Confusing issue with Engine & Resource stages

### ISSUE THREAD

**Issue by jwvanderbeck** [krpc/krpc#274]
So I am running into a very confusing issue.  kRPC is returning information that tells me the engine is in one stage but the fuel the engine uses is in another stage.

I have a two stage craft, with staging like this:
5) First stage engine
4) Launch clamps
3) retro and ullage, as well as interstage fairings
2) second stage engines (2)
1) Payload fairings
0) Payload sep

Now I am working through a routine to calculate the burn time of each stage *in isolation*.  And what I am seeing when I query the vessel data is the engine will be returned in one stage but the fuel in the **next** stage.  For example the first stage engine shows up in stage 5 as expected, but the fuel used by that engine is returned in stage **4**.

```
Stage  5
========
liquidEngineprodulVR2
thrust  1296058.5
propellantMass  0
isp  290.0
Stage 5 burn time 0.0 seconds

Stage  4
========
Kerosene
LqdOxygen
Kerosene
LqdOxygen
PSPC
PSPC
PSPC
PSPC
thrust  0
propellantMass  72776.6888842
isp  0.0
Stage 4 burn time 0.0 seconds

Stage  3
========
sepMotor1
sepMotor1
sepMotor1
sepMotor1
SnubOtron
SnubOtron
SnubOtron
SnubOtron
thrust  414394.234375
propellantMass  0
isp  246.436773527
Stage 3 burn time 0.0 seconds

Stage  2
========
liquidEngine
radialEngineMini
thrust  258819.23584
propellantMass  0
isp  309.366414193
Stage 2 burn time 0.0 seconds

Stage  1
========
ElectricCharge
ElectricCharge
Kerosene
LqdOxygen
Kerosene
LqdOxygen
Kerosene
LqdOxygen
PSPC
PSPC
PSPC
PSPC
thrust  0
propellantMass  30062.4003087
isp  0.0
Stage 1 burn time 0.0 seconds
```

```
	def StageVacuumSpecificImpulse(self, stage):
		thrust = 0
		fuelConsumption = 0
		vessel = self.vessel
		allEngineParts = vessel.parts.with_module("ModuleEnginesRF")
		for part in allEngineParts:
			if part.stage == stage:
				thrust += part.engine.max_thrust
				fuelConsumption = fuelConsumption + (part.engine.max_thrust / part.engine.vacuum_specific_impulse)
		if fuelConsumption <= 0.0:
			return 0.0
		else:
			return thrust / fuelConsumption


	def StageBurnTime(self, stage):
		# tonnes of propellant * Isp * 9.80665 / thrust
		# build a list of propellants used by all engines in the stage
		print ""
		print "Stage ", stage
		print "========"
		vessel = self.vessel
		Isp = self.StageVacuumSpecificImpulse(stage) # seconds
		thrust = 0 # newtons
		allEngineParts = vessel.parts.with_module("ModuleEnginesRF")
		stagePropellants = []
		for part in allEngineParts:
			if part.stage == stage:
				print part.name
				thrust += part.engine.max_thrust
				for prop in part.engine.propellants:
					if not prop in stagePropellants:
						stagePropellants.append(prop)
		# get a list of all resources in the stage
		allResources = vessel.resources_in_decouple_stage(stage, cumulative = False).all
		propellantMass = 0
		for resource in allResources:
				print resource.name
				propellantMass += (resource.amount * resource.density)
		print "thrust ", thrust
		print "propellantMass ", propellantMass
		print "isp ", Isp
		if thrust > 0.0:
			return propellantMass * Isp * 9.80665 / thrust
		else:
			return 0.0
```

**Comment by jwvanderbeck** [comment]
In talking with @NathanKell it seems this isn't really the right way for me to be going about doing what I am trying to do, but instead I should be getting the Propellant object from the engines, then getting the data from there as that would give me the ones actually connected to the engines.

kRPC doesn't seem to encapsulate the Propellant class though.  At best it simply returns the name of the propellants used in an engine, which really doesn't help in this case since that doesn't tell you what is actually connected or not.

**Comment by NathanKell** [comment]
Yeah, the point of the engine's Propellant objects is to track the total resources available to the engine and the total resource capacity for those resources. It's how the in-flight gauges are constructed for engines. But it's also _exactly_ what you want if you want to know "how much propellant is there for me to burn" in other circumstances too.

**Comment by jwvanderbeck** [comment]
I've started roughing out a Propellant's service, but the instructions for compiling kRPC look extremely daunting.

I'll post back when i've got the service finished, but not sure i'll be able to compile and test.

**Comment by djungelorm** [comment]
Cool.

FYI you don't need to build the entirety of kRPC to add a service to the python (or lua) clients. Just write your service, build it and link it against KRPC.dll (and maybe KRPC.SpaceCenter.dll if you want to reuse the vessel class etc), and put the resulting dll somewhere in gamedata. The python client is dynamic so will automatically pick up the new service when it connects.

**Comment by jwvanderbeck** [comment]
I guess I could do that to test it out, so thanks!

Ideally though when done this would be added to the core so everyone can use it :)

**Comment by djungelorm** [comment]
Yeah, that was my intention - and I'd be more than happy to merge what you come up with into the SpaceCenter service!

**Comment by jwvanderbeck** [comment]
Got a basic class here, think it covers everything: https://github.com/jwvanderbeck/krpc/blob/master/service/SpaceCenter/src/Services/PropellantResource.cs

I also added a property to the Engine service to get the propellants:
https://github.com/jwvanderbeck/krpc/blob/master/service/SpaceCenter/src/Services/Parts/Engine.cs#L232

The property naming on that last one is a bit wonky, given there is already a Property named "Propellants" that returns the NAMES rather than the actual propellants.  In an ideal world that would be changed to PropellantNames and then Propellants would return, well the propellants, but that would be a breaking change so probably not desired.  Your call though, I know some projects would embrace the breakage for the sake of clarity others wouldn't.  Up to you :)

**Comment by djungelorm** [comment]
Wow that was fast! Thanks. I prefer clarity - so we can rename it to PropellantNames.

I'm a bit busy over the next few days, but should have some time to look at your changes next week.

**Comment by jwvanderbeck** [comment]
PR for the new stuff is here:
https://github.com/krpc/krpc/pull/275
