### ISSUE TITLE
PID Can be a bit wonky sometimes..

### ISSUE THREAD

**Issue by jwvanderbeck** [krpc/krpc#279]
I'm curious what RPC is using for steering PID? Is it using stock's PID or its own?  KSP in general after 1.1 is going through PID teething issues.  Some like kOS's PID seem rock solid, while others including Stock's, MJ's, and kRPC's are rather wonky and prone to over correcting and bad oscillation.  MJ seems to have gotten a lot better in a recent dev release.

This might also be more exaggerated for Realism Overhaul players like myself that don't have god mode reaction wheels :)

As an example I have a craft right now with an upper stage and some 1kn RCS.  If this craft is far off prograde and I tell kRPC's AP to hold prograde, it will take literally about 15 minutes to finally settle, as it overcorrects time and time again.

I know this issue is a bit vague at the moment, and I can provide much more detail information and even craft files if it helps, but I kind of just wanted to get the thought ball rolling first and find out if kRPC for one even uses a custom PID or not?

**Comment by djungelorm** [comment]
kRPC uses a custom PID and indeed, it is very wonky. But it works "well enough" that fixing it hasn't been high on my priority list.

The current PID doesn't do any auto-tuning of its gains, so I agree the problems are probably more pronounced with RO installed, as the gains were tuned with a simple stock rocket.

A few months back I taught myself some proper control theory, and came up with an auto-tuning roll controller that (with some limited testing) appears to work very well.
https://gist.github.com/djungelorm/98b59370a1d171817edb
I even wrote up the mathematics for how it works: https://docs.google.com/document/d/1glHxqjsmae3Tep-oFe8f5QYs6BUrc5dKkSrVJMopw_c/edit?usp=sharing

As far as I'm aware, kOS does something similar to above, but in all three axes. I had a go at extending this to the other 2 axes, but came across issues with discontinuity in angles (e.g. heading suddenly flipping from 360 -> 0) Hopefully I'll find some time to get this working (probably as a python script initially before I port it to C# to replace the old autopilot).

**Comment by djungelorm** [comment]
The new autopilot has been released in 0.3.5. Should fix these issues.
