### ISSUE TITLE
Enum naming doesn't get translated to client standards?

### ISSUE THREAD

**Issue by jwvanderbeck** [krpc/krpc#280]
Classes and Methods all get converted to underscore_format in the Python client.  IE ReferenceFrame becomes reference_frame and SpaceCenter becomes space_center.

Yet the Enum UI.MessagePosition remains as MessagePosition

**Comment by djungelorm** [comment]
```connection.ui.MessagePosition``` is an enum class, so it's CamelCase, just like other classes such as ```connection.space_center.Vessel```. Its fields, e.g. ```connection.ui.MessagePosition.top_left```, are then snake_case.

So this follows the classes are CamelCase and members are snake_case convention correctly?
