### ISSUE TITLE
UI elements should have the option to remain visible even if KSP UI is disabled

### ISSUE THREAD

**Issue by jwvanderbeck** [krpc/krpc#281]
I want to use these to provide information overlays while hiding the KSP UI.  Given that all the UI elements have an explicit `visible` property, it would seem to me that they should remain visible even if the KSP UI is hidden, so long as the UI element has `visible = True`.  If not that, then some other setting to enable them to remain visible, even if it is a top level property of the UI service.

**Comment by djungelorm** [comment]
The UI elements are currently added to KSPs stock UI canvas, which is what's being hidden. I think the best way to allow this use case would be to add methods to create your own canvases. That way you could also group items and hide/unhide them separately from KSPs canvas.

**Comment by jwvanderbeck** [comment]
Yeah looked at the code thinking I would add this function myself and it looks like as you say, will need to crate a new canvas.  IIRC you can have multiple canvases in Unity.

**Comment by djungelorm** [comment]
Yep you can have multiple. And I think creating them is as simple as:
```
var canvas = new GameObject ("canvas", Canvas);
canvas.RectTransform.width = screen.width;
canvas.RectTransform.height = screen.height;
```

**Comment by jwvanderbeck** [comment]
I have a working test right now with just using a new canvas for all elements rather than KSP's.

**Comment by jwvanderbeck** [comment]
For reference:

                    CanvasInstance = new GameObject ("krpc.canvas", typeof(Canvas));
                    UnityEngine.RectTransform transform = CanvasInstance.GetComponent<UnityEngine.RectTransform> ();
                    UnityEngine.Canvas canvas = CanvasInstance.GetComponent<UnityEngine.Canvas> ();
                    canvas.renderMode = RenderMode.ScreenSpaceOverlay;
                    transform.sizeDelta = new Vector2 (Screen.width, Screen.height);
                    return CanvasInstance;

**Comment by djungelorm** [comment]
I've updated the API to include a Canvas object - which you must create before adding UI objects. There is a UI.AddCanvas for creating canvases, and a UI.StockCanvas property to get the stock canvas.

I've also copied the AddText, AddButton etc. methods from the Panel class to the Canvas class so you can add elements to a canvas without needing a panel.

**Comment by jwvanderbeck** [comment]
Nice!  Guess I can stop using my version then :)

**Comment by jwvanderbeck** [comment]
Hey @djungelorm one thing I found out after I posted here last is that KSP has its own GraphicsRaycaster which needs to be used instead of the Unity default one, or else you can't interact with the UI.  So the code I gave above for creating the canvas is not 100% working.  Instead you need to create a blank GO and add the proper components on manually including a KSPGraphicsRaycaster. 

Not sure if you ran into this or not, just wanted to mention it in case you didn't.

**Comment by djungelorm** [comment]
Just saw your comment about raycasters. Will investigate

**Comment by djungelorm** [comment]
Should be working now :)
