### ISSUE TITLE
Feature request: extend part API to allow adding forces at position through KRPC

### ISSUE THREAD

**Issue by finger563** [krpc/krpc#287]
using the `part.rigidbody.AddForceAtPosition(force, position, ForceMode);` API

**Comment by finger563** [comment]
If you can point me to some relevant places to make the change (most notably in the server code and in the C++client code, which I use) then I'll fork and make the changes :)

**Comment by djungelorm** [comment]
I actually have this implemented. It almost made it into the last release, but I ran out of time to test the changes. Will get them committed as soon as I can.

**Comment by finger563** [comment]
Oh, thanks! Will be quite helpful for some hardware-in-the-loop stuff we're doing :)

**Comment by djungelorm** [comment]
I've added two new APIs for this:
 - Part.AddForce - this adds a force that acts on the part. It returns a force object that can be used to modify or remove the force. The force acts until it is removed.
 - Part.InstantaneousForce - this adds an "instantaneous" force on the part. The force is applied on the next physics tick, then removed.

**Comment by finger563** [comment]
Does this mean that the c++ API supports this feature?

**Comment by djungelorm** [comment]
Yep. It's supported in all clients. Let me know if you want me to write you an example program.

**Comment by djungelorm** [comment]
Also just noticed this hasn't been released yet... will be in the next version (0.3.6)

**Comment by finger563** [comment]
Haha thanks, can I probe you for an ETA? :)

**Comment by djungelorm** [comment]
Probably some time next week. In the mean time you can use this dev build which has the new API: http://krpc.s3-website-us-east-1.amazonaws.com/deploy/master/606.1/

**Comment by finger563** [comment]
Thanks a lot for the dev build link :) 👍
