### ISSUE TITLE
AutoTuning AutoPilot

### ISSUE THREAD

**Issue by djungelorm** [krpc/krpc#289]
An overhauled version of the autopilot has been implemented and is ready for testing. Feedback welcome! It automatically tunes its PID parameters to the vessels MoI and available torque, which should fix many of the issues with overshoot, oscillation and jiggling engine nozzles!

I've tried it out with vessels of various sizes and it seems pretty solid. The API is largely unchanged, so existing scripts should "just work". The only exception is that the API to manually tune the PID parameters has changed.

* [Plugin download](https://krpc.s3.amazonaws.com/deploy/feature/autotuning-autopilot/544.1/krpc-0.3.4-83-g2b4e54b.zip)
* [New API documentation](http://krpc.s3-website-us-east-1.amazonaws.com/deploy/feature/autotuning-autopilot/544.1/doc/)
* [Documentation for the PID internals](http://krpc.s3-website-us-east-1.amazonaws.com/deploy/feature/autotuning-autopilot/544.1/doc/tutorials/autopilot.html)

Related issues: #212, #279, #233, #163

**Comment by jwvanderbeck** [comment]
Sounds awesome! Can't wait for the next release.

**Comment by mattbradley** [comment]
I'm curious what types of vessels you tried the new autopilot on. I tried a couple of different ones, and its performance was mediocre. Ships would sometimes spin out of control on take-off. When they did launch without crashing, the yaw, pitch, and roll controls were very twitchy. The vessels performed fine with SAS.

I uploaded a video demonstrating some of my problems: https://youtu.be/CrNTBkpym9I

It's been a while since I've studied control theory, so hopefully you'll have more insight into the problems than I do. Let me know how I can help or if you need any more info.

**Comment by djungelorm** [comment]
I've tried launching the Kerbal-X with various combinations of gimballing/control surfaces/reaction wheel torque enabled and disabled, and rockets of various sizes when in orbit using reaction wheels to orientate the vessel.

Looking at the control inputs in the bottom left, it looks like some of your examples go a bit mental in the first moments of the launch. This is probably caused by the available torque suddenly changing from 0 to a large number when that gimballed engine ignites. My launch script for the kerbal-x waits until the engines are throttled up before the clamps are released - so the available torque never jumps by a significant amount. So I wonder if your rocket will leave the pad reliably if you wait a bit before releasing the clamps? A possible fix for this if it is the case might be to damp the available torque value.

On all the other launches the control inputs look very jittery. Not sure why but will try and reproduce. Can you try increasing the time to peak to see if the jitters go away?

**Comment by mattbradley** [comment]
I forgot to mention that I'm running Realism Overhaul. Perhaps there is something in that collection of mods that is throwing off the controller.

I do wait a couple of seconds until the engines are throttled up before the clamps are released in my launch script. Also, I don't engage autopilot until after the clamps are released. Could it be an issue with a zero or very low integral term right after autopilot is engaged?

I will try increasing the time to peak tomorrow. I'll also try running the autopilot on stock KSP with stock vessels to make sure it's working correctly in an environment similar to yours.

**Comment by djungelorm** [comment]
I've only run it in stock. Not sure what effect RO will have. The code uses the new ITorqueProvider logic so I think it should work ok with RO. I've also noticed that the autopilot tries to turn the vessel when it's just sat on the pad facing the correct direction!

**Comment by mattbradley** [comment]
Another thing I forgot to mention. Setting the target roll to 0 just set the vessel spinning around and around. It seemed to always think the roll error was 90 degrees.

**Comment by jwvanderbeck** [comment]
> Another thing I forgot to mention. Setting the target roll to 0 just set the vessel spinning around and around. It seemed to always think the roll error was 90 degrees.

This is sadly not new, as kRPC does this with the existing PID as well.  I ran into it this weekend.  If the rocker is in a vertical ascent, setting any roll other than -90 just causes an infinite roll.

**Comment by jwvanderbeck** [comment]
The main differences in RO is less control authority.  Vessels typically don't use reaction wheels, and rely more on RCS for attitude control in space.  During launch typically gimballed engines, sometimes extra vernier engines, and winglets is about all you have for control.

Any chance of getting a pre-release or even a dropbox link to a DLLI could try out to help test this?  I just can't seem to compile this on my own on my Mac.

**Comment by mattbradley** [comment]
@jwvanderbeck does the link the original issue not work? https://krpc.s3.amazonaws.com/deploy/feature/autotuning-autopilot/518.1/krpc-0.3.4-38-ga53f223.zip

**Comment by jwvanderbeck** [comment]
It probably does and I am just completely blind!

Will check it out after work.

**Comment by djungelorm** [comment]
FYI I'm working on some changes that will hopefully fix the issues found so far. Will hopefully have it ready this evening.

**Comment by jwvanderbeck** [comment]
Well at first testing this seems like a step back.  Previously I had no real issues with craft during ascent, just in space.  With this new one my rocket can't even ascend without flopping all over the place.  It is only a single test so far, I need to try different vehicles, then compare to previous again, but yeah those are my first thoughts.

**Comment by jwvanderbeck** [comment]
I'm seeing high frequency spikes in the control settings.  I too am seeing the weird pegging of the controls before launch, even though the AP is set to a vertical ascent.

Here is a recorded video:
https://www.youtube.com/watch?v=vwUEHiJgTKA

**Comment by djungelorm** [comment]
Thanks for all the testing :) In _theory_, this autopilot should be better than the old one, hopefully it's just a case of getting the implementation sorted! I'm working on a bunch of changes - download coming soon... Here's what I'm working on:

1) The way the target rotation velocity is calculated is being rewritten to be computed from a quaternion representing the target rotation, instead of a direction vector and roll angle. This will allow the autopilot to hold a chosen roll angle when it is pointing straight up.

2) A low-pass filter will be applied to the target rotational velocity before it is passed to the controller, such that the change in the rotation acceleration is within the capabilities of the vessels angular acceleration. This should helps remove the derivative kick when the target direction is suddenly changed. I'm doing it like this rather than using a derivative term in the controller, because they are PI controllers with no derivative term! (and they have to be so that it is a second order system, which is easy to auto-tune)

3) When sitting on the launchpad, the integral terms for the rotation rate PI controllers will be fixed to 0. This should prevent the massive sudden control input when the clamps are released, due to build up of the integral term.

4) When the available torque / moi ratio is close to zero, the vessel is basically uncontrollable. In this case the autotuning will pause -- otherwise the PI gains would get excessively large and there could be a division by zero in the tuning code. Also, the integral term for the PI controllers will be fixed to 0, for the same reasons as the case when the vessel is on the launchpad.

5) The autopilot will only try to rotate to the target roll angle when the pitch and yaw are within 10 degrees of the target direction. This will hopefully help when the autopilot is trying to regain control of a vessel that's spinning wildly out of control, as it won't be shooting itself in the foot by trying to roll as the roll angle is couple to pitch/yaw and will therefore change very rapidly.

6) I found a bug with the available torque and MoI calculations using the wrong reference frame... This will have affected the PI tuning in the previous version which doesn't help things!

**Comment by jwvanderbeck** [comment]
Well most of that is way over my head but it sounds great!

Just to add data points, I just launched the exact same rocket with the exact same script, but using the old PID and the ascent was butter smooth.

I agree this PID should be better in the long run, we just need to get it set up right :)

**Comment by djungelorm** [comment]
Helps me get my thoughts together by writing things down so thought I may as well post all the details!

I just did a quick test of my changes with the long rocket lifting off the launch pad - and it went very smoothly! Up until the point when I deliberately put it into a flatbed spin which it struggled with... I'm going to try adding a "panic mode" which will set the target rotation speed to 0 if the rotation speed is very high, and not bother trying to aim in a particular direction until the rocket is rotating at a reasonable speed.

**Comment by djungelorm** [comment]
Here's a new version for you to try:
https://krpc.s3.amazonaws.com/deploy/feature/autotuning-autopilot/524.1/krpc-0.3.4-48-ga487df4.zip

I've also updated the links up top. Please try and break it ;)

I've tested it with my ascent program and a few different sizes of rockets, and a few different craft in orbit. They all worked perfectly! Only thing I noticed is that it rotates towards the target direction quite slowly, so the default max rotation rate should probably be increased. I also tried an aircraft takeoff + level flight program with the Aeris 3a and the Mallard which worked ok (with time to peak set to 10, as there's a lot of wobble with the default of 3 seconds)

I implemented ideas 1, 3, 5 and 6 from above. I've not implemented idea 2, or the "panic mode" yet - but their omission doesn't appear to be a problem in the tests I ran. I'll need to implement idea 4, as currently you'll get division by zero errors if your craft has no torque.

**Comment by mattbradley** [comment]
I took a few minutes to test the rockets from my earlier video with the new build. The launches and ascents were rock-solid. No problems at all!

I'll try to break it later tonight. Good work so far!

**Comment by jwvanderbeck** [comment]
Yep my initial tests show the same.  Rock solid performance.  Same rocket that I showed above in the video, with the changes is just as solid as it is with the old PID.

**Comment by djungelorm** [comment]
Here's another version - hopefully the final one! _fingers crossed_
https://krpc.s3.amazonaws.com/deploy/feature/autotuning-autopilot/529.1/krpc-0.3.4-56-g5a15ac6.zip

I'm still working on the documentation (with diagrams etc.) but basically it works the same as the previous version, but with a better target velocity curve so that the vessel turns towards the target more quickly.

The previous version used a linear velocity curve which meant that the vessel turned towards the target with deceasing acceleration. But its faster to turn with constant acceleration, which is what the new curve (a square root function) does.

There was also a problem in the old version that the controls would oscillate when the vessel was pointing in the correct direction, and this problem became even worse with the new, more aggressive, velocity curve. I'll explain how this is overcome in the docs as it needs a diagram...

**Comment by djungelorm** [comment]
I've merged the changes into master.

Final dev version is here in case you want to try things before the next release (in a few days):
https://krpc.s3.amazonaws.com/deploy/feature/autotuning-autopilot/544.1/krpc-0.3.4-83-g2b4e54b.zip

Also documentation on how it all works and how to configure it (with diagrams!) is here:
http://krpc.s3-website-us-east-1.amazonaws.com/deploy/feature/autotuning-autopilot/544.1/doc/tutorials/autopilot.html

**Comment by jwvanderbeck** [comment]
> There was also a problem in the old version that the controls would oscillate when the vessel was pointing in the correct direction, and this problem became even worse with the new, more aggressive, velocity curve. I'll explain how this is overcome in the docs as it needs a diagram...

So with the latest version I am indeed suffering this tendency to oscillate around the target vector.  It seems less if the rocket has solid roll control, but even then it can be really bad at certain flight profiles.  You mentioned that this was to be expected and you would include documentation on how to overcome it.  I've read the new documentation but a lot of it goes over my head i'm afraid.  Can you maybe provide a dummies guide to fixing this specific issue?

**Comment by jwvanderbeck** [comment]
Actually scratch that.  I re-read it and I think attention_angle is what I needed.  I apparently was just too sleepy to notice it last night.
