### ISSUE TITLE
Couple of ReferenceFrame feature requests

### ISSUE THREAD

**Issue by jwvanderbeck** [krpc/krpc#290]
It would be great if the ReferenceFrame class could expose a couple of things to other kRPC service code:

1. The type of reference frame.  This data already exists but is private.
2. The underlying transform of the reference frame.  I'm not sure if all types would have one, but most of them should.

For point 2 what I mean is that the underlying ReferenceFrame object, be that a Vessel, a CelestialBody, or a Part all are ultimately GameObjects an therefore have a Transform property.  EG ReferenceFrame.InternalPart.transform, or ReferenceFrame.InternalVessel.transform.  Now you can currently get those two by getting the Internal* which is exposed, and then grabbing the transform but it requires knowledge of the type.  Others like CelestialBody ones though, the underlying body is not exposed that I see.   Furthermore it would be best if knowledge of RefFrame type was not required here.  You just want a transform.

I'm not sure if these make sense?  Should be easy to implement and I could probably make a PR for it.

**Comment by djungelorm** [comment]
Sure thing! Makes sense. Probably just a case sprinkling public in a few places and adding some documentation - I have the build system set up so that all public members have to be documented. Helps remind me to document things!

**Comment by djungelorm** [comment]
Also thanks for the offer, but probably best if I make the changes - they're not big and I'm best placed to write the documentation.

**Comment by djungelorm** [comment]
Added in the above commit. Should expose everything you need. There isn't really a single transform per se, a reference frame consists of the following (all relative to KSPs world space):
- Position of the origin,
- Rotation of the axes relative,
- Linear velocity of the frame,
- Angular velocity of the frame,
and you can get all these via public properties.

**Comment by jwvanderbeck** [comment]
Like I said, when I say Trasform I literally me the underlying GameObject.transform, IE InternalVessel.transform, or InternalPart.transform, or body.transform

**Comment by djungelorm** [comment]
Oh right I see. You could get hold of them via something like ReferenceFrame.InternalVessel.transform. Currently there's only ReferenceFrame.InternalVessel and ReferenceFrame.InternalPart. I'll add properties for all the other types of object.

**Comment by jwvanderbeck** [comment]
Right, but be a lot better abstracted away so the caller can not care what type the internal reference frame is if it doesn't want to since the return is always going to be a Transform.

**Comment by djungelorm** [comment]
Yes I see your point!

**Comment by djungelorm** [comment]
There we go! Only case that doesn't have a transform (that I'm aware of) is a maneuver node.
