### ISSUE TITLE
Feature Request: PHP as an available language?

### ISSUE THREAD

**Issue by bgarrison25** [krpc/krpc#291]
I noticed you have python and lua. I figured it couldn't be too hard to include php. Any chances of this happening?

**Comment by djungelorm** [comment]
Yeah there's a chance - if people want it! The only difficult bit is whether there is a decent protobuf library for php. Google don't provide an official one.

**Comment by bgarrison25** [comment]
https://github.com/drslump/Protobuf-PHP

**Comment by bgarrison25** [comment]
I would LOOOOVE it. I've been developing in php for over 10 years so it would be nice. I know LUA as well but its such a limited language

**Comment by djungelorm** [comment]
I'm going to be away the next two weeks, so won't be able to work on this just yet. But consider this on the todo list ;)

Also, if you want to have a crack at writing the client yourself, the communication protocol is documented here and contains everything you should need: http://krpc.github.io/krpc/communication-protocol.html

**Comment by djungelorm** [comment]
FYI I'm working on adding [gRPC](http://www.grpc.io/) support, which will add support for many more languages including PHP.

**Comment by djungelorm** [comment]
#123

**Comment by bgarrison25** [comment]
That is awesome! Thanks!

**Comment by djungelorm** [comment]
gRPC not looking possible due to implementation issues with getting it to work in C#.

Closing this, there are no plans to work on an "official" PHP client right now, but if someone wants to write one and contribute it feel free!
