### ISSUE TITLE
Investigate new MoI code in KSP 1.1.3

### ISSUE THREAD

**Issue by djungelorm** [krpc/krpc#293]
Do the moi changes in KSP 1.1.3 mean that the custom MoI code can be removed?

**Comment by djungelorm** [comment]
Related issue: #212

**Comment by dewiniaid** [comment]
I believe kOS removed its MOI workaround in the current RC; related issue is https://github.com/KSP-KOS/KOS/issues/1680

**Comment by djungelorm** [comment]
The KSP provided MOI values still seem to be broken. Here's simple example. For a single structural fuselage part (which I chose as it has mass, and no complicated resources etc.) I get the following:

```
Vessel.MOI:  (447, 447, 308)
Custom code: (447, 308, 447)
```
(the values return by Vessel.MOI are multiplied by 1000 to be the same units as the custom code, but that shouldn't matter)

Looks roughly OK. The Vessel.MOI just appears has the roll and yaw values swapped - the order for the custom code is pitch, roll, yaw. The part is rotationally symmetrical around the roll axis, so you'd expect the pitch and yaw values to be the same, which they are. And given it's shape the MOI around the roll axis should be smaller, which it is.

But with two structural fuselage parts stacked on top of each other I get:

```
Vessel.MOI:  (1069, 893, 791)
Custom code: (1069, 615, 1069)
```

You'd expect the MOI around the roll axis to have doubled, which it does with the custom code (308*2 = 615). But Vessel.MOI appears to return garbage for the roll and yaw axes! As the combined parts are effectively the same shape as before, you'd expect the MOI around pitch and yaw to be the same, which they are for the custom code but not for Vessel.MOI. Also you'd still expect the MOI around roll to be less than the other axes, which it is for the custom code, but not for Vessel.MOI - the roll value is in fact larger than the yaw value!

@NathanKell - any ideas what's going on here?

**Comment by NathanKell** [comment]
The KSP code has a spurious rotation. Removed, it is fairly sane. @lamont-granquist and @sarbian can speak more to this.
