### ISSUE TITLE
UI.Text.alignment using incorrect Enum?

### ISSUE THREAD

**Issue by jwvanderbeck** [krpc/krpc#295]
The UI.Text.alignment property currently takes a TextAnchor enum not a TextAlignment enum which seems incorrect.

If it *is* correct, then the naming seems wrong and then the second question would be how *do* you apply text alignment `right, left, center`, because I see no other property for it.

**Comment by djungelorm** [comment]
I followed the naming conventions in the Unity API, as the UI RPCs map directly to it: https://docs.unity3d.com/ScriptReference/UI.Text-alignment.html

You can apply the alignment by assigning to the property. For example in python:
```mytext.alignment = conn.UI.TextAnchor.upper_left```

**Comment by jwvanderbeck** [comment]
So then what is the `UI.TextAlignment` enum used for?

**Comment by djungelorm** [comment]
It's used for Text.Anchor in the Drawing service (http://krpc.github.io/krpc/csharp/api/drawing/text.html#property-KRPC.Client.Services.Drawing.Text.Anchor) which I now realize is confusing as the enum should probably be defined in the Drawing service not the UI service!

**Comment by jwvanderbeck** [comment]
So what you are saying is that the `Text.anchor` property takes a `TextAlignment` enum. And the `Text.alignment` property takes a `TextAnchor` enum?

**Comment by djungelorm** [comment]
Apologies there was a typo in my previous comment... It's as follows:
- Drawing.Text.Alignment returns UI.TextAlignment
- Drawing.Text.Anchor returns UI.TextAnchor
- UI.Text.Alignment returns UI.TextAnchor

**Comment by djungelorm** [comment]
And that naming matches up with the corresponding Unity API:
http://docs.unity3d.com/ScriptReference/TextMesh-alignment.html
http://docs.unity3d.com/ScriptReference/TextMesh-anchor.html
http://docs.unity3d.com/ScriptReference/UI.Text-alignment.html
