### ISSUE TITLE
[Request] Non-Blocking method to enter timewarp

### ISSUE THREAD

**Issue by jwvanderbeck** [krpc/krpc#302]
Best I can tell the only way to currently TimeWarp from kRPC is using SpaceCenter.WarpTo which warps to a specific UT but is a blocking call.

I would like to be able to simply enter TimeWarp with a given rate, but in a non-blocking way so I can continue to check values and monitor for conditions, and then drop out of TimeWarp when conditions are met.

Ideally I think a method to enter TimeWarp which returns maybe a TimeWarp object.  That object would have properties for get/set the timewarp rate and for exiting timewarp.

**Comment by djungelorm** [comment]
You can do this by setting the [SpaceCenter.RailsWarpFactor](http://krpc.github.io/krpc/csharp/api/space-center/space-center.html#property-KRPC.Client.Services.SpaceCenter.SpaceCenter.RailsWarpFactor) or [SpaceCenter.PhysicsWarpFactor](http://krpc.github.io/krpc/csharp/api/space-center/space-center.html#property-KRPC.Client.Services.SpaceCenter.SpaceCenter.PhysicsWarpFactor) properties. For example, to warp at 1000x on-rails, in python, do:
```conn.space_center.rails_warp_factor = 5```

Apologies if the documentation was not clear?

**Comment by jwvanderbeck** [comment]
Ah no, my apologies.  I saw RailsRate and WarpRate as ReadOnly and didn't notice the others that could be read or set.
