### ISSUE TITLE
no way to compute mach number with FAR

### ISSUE THREAD

**Issue by Assert1** [krpc/krpc#313]
Mach number, is a key value of all aerodynamics processes, and everyting is linearized about it. It is required for any process modeling, but it can't be computed from the API with FAR installed.

**Comment by djungelorm** [comment]
Unfortunately this isn't exposed via FAR's public API :( I'll open a ticket with FAR and see if we can get it added.

**Comment by djungelorm** [comment]
Actually scratch that last comment, it is available, just via a PartModule instead of the FARAPI!
