### ISSUE TITLE
Python client: Bazel BUILD file breaks pip install from source on Windows

### ISSUE THREAD

**Issue by dewiniaid** [krpc/krpc#321]
I was going to test out some changes to the Python client that I was working on and encountered issues with pip failing to install it:

```
(venv) D:\git\ksp-mission-scripts>pip install D:\git\krpc\client\python --upgrade --no-deps  --no-cache-dir
Processing d:\git\krpc\client\python
Installing collected packages: krpc
  Running setup.py install for krpc ... error
    Complete output from command d:\git\ksp-mission-scripts\venv\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Daniel\\AppData\\Local\\Temp\\pip-qdixyusp-build\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\Daniel\AppData\Local\Temp\pip-m91p1ftd-record\install-record.txt --single-version-externally-managed --compile --install-headers d:\git\ksp-mission-scripts\venv\include\site\python3.5\krpc:
    running install
    running build
    running build_py
    creating build
    error: could not create 'build': Cannot create a file when that file already exists
```

The issue seems to be a conflict with Bazel's BUILD file; I suspect only on Windows since the names do not collide elsewhere due to case sensitivity.  Renaming BUILD to something else allows pip to install successfully.

**Comment by djungelorm** [comment]
I'm not sure what pip does when you point it a directory, but you could try using `client/python/setup.py` to generate a zip and install that using pip? However, this probably won't work either. The way I building and install the python client for testing is to do:
```
bazel build //client/python
pip install bazel-bin/client/python/krpc-VERSION.zip --upgrade --no-deps  --no-cache-dir
```
The Bazel build command is needed to generate and add a few things to the client, including the compiled protobuf files, version numbers, changelogs etc. Just installing from the source in client/python/... or using setup.py alone would miss these.

**Comment by djungelorm** [comment]
Closing as running pip directly is unsupported. Bazel should be used to generate the python package.
