### ISSUE TITLE
invalid vessel.thrust() for AB engines

### ISSUE THREAD

**Issue by Assert1** [krpc/krpc#327]
vessel.thrust() (and engine.thrust) returns an invalid (fixed, max theoretical?) value for (at least) mixed mode engines (like RAPIER) in air breathing mode.

**Comment by djungelorm** [comment]
The fuel flow and velocity curves weren't being used correctly when computing thrusts for air breathing engines. I've also changed vessel.thrust to just return engine.finalThrust from the KSP API, instead of computing it manually.
