### ISSUE TITLE
Consistent atmosperic and aerodynamic data

### ISSUE THREAD

**Issue by Assert1** [krpc/krpc#328]
Some methods is not avail with FAR, but it is possible to compute required data from available data and make things more transparent.

- flight.static_pressure() can be computed from dynamic pressure and mach number (basic thermodynamics) as with flight.speed_of_sound().
- also, static pressure at sea level is requred very often to model the atmosphere.
- flight.aerodynamic_force() can be computed from the coefficients (because FAR internally computes them from forces), so lift=Q\*cl\*are, drag=Q\*cd\*area, area=mass/(bc\*cd), etc
- angle of attack and sideslip is also very usefull things, i think it will be great if we can add it to the API.

I can compute everyting from presented values at this moment, but it is requred alot of computations and leafs for FAR and standard aerodynamics. I think this can be hidden from the user completly.

**Comment by djungelorm** [comment]
Sounds good. Would you be able to post your code for calculating these values so I can port it into the server?

**Comment by Assert1** [comment]
dp=flight.dynamic_pressure();
tc=flight.total_air_temperature();
ts=flight.static_air_temperature();
mach=flight.mach();

tr=tc/ts; // temperature ratio
hr=(2*(tr+sqr(mach)/2-1))/sqr(mach); // ratio of specific heats (https://en.wikipedia.org/wiki/Heat_capacity_ratio)
pr=pow(tr, hr/(hr-1)); // pressure ratio
pc=(dp+1); // total air pressure
ps=pc/pr; // static pressure
a=sqrt(hr*ps/rho); // speed of sound

EAS is a function of static air pressure at sea level, but this is a general property that can't be calculated from current conditions as values above, so you need to find p0 somewhere in KSP... this is a realy meaningfull thing...

In case of FAR, to compute lift and drag force:
cd=flight.drag_coefficient();
cl=flight.lift_coefficient();
bc=flight.ballistic_coefficient();
area=vessel.mass()/(bc*cd);
lift=cl*area*dp; // mul to lift direction
drag=cd*area*dp; // mul to drag direction

Suddenly, i already found an angle of attack and sideslip in the API, skipping this...

**Comment by djungelorm** [comment]
I think that should be all of the stuff added. Let me know if I missed anything!
