### ISSUE TITLE
documentation: Forces are expressed in Newtons when (from testing) it seems like they are actually in kN

### ISSUE THREAD

**Issue by finger563** [krpc/krpc#329]
The documentation for forces states that the units are in Newtons (N), but based on the mass model (in which 1.0 = 1000 kg), it would appear that the forces are actually in kN. (This applies to the documentation for the AddForce methods as well)

**Comment by Assert1** [comment]
Also for dynamic pressure, it is actually in kPa, but Pa in docs...

**Comment by djungelorm** [comment]
Will change the code to match the documentation, as that was the intended behaviour.
