### ISSUE TITLE
Fix science subject methods operating on active vessel 

### ISSUE THREAD

**Issue by Croissong** [krpc/krpc#338]
Thanks for all the cleanup on my  PR #337 ! I did however use the active vessel on purpose because if you for example EVA, the kerbal's situation is relevant for the experiment. c48ef327159e38af4a0a2c26683cdbfa4f4fe3d4

**Comment by djungelorm** [comment]
Is this just for the case where you want to run a crew report from an EVA kerbal? Does it affect any experiment that are performed by parts?

I think a cleaner approach would be to have a Kerbal object (similar to the Vessel object) which is used to interact with experiments, among other things (like the Kerbal's RCS backpack which can't currently be controlled through the mod). Interacting with Kerbal based experiments via a Part object doesn't make sense to me...

**Comment by Croissong** [comment]
Ok you're right, Kerbal objects would make a lot of sense.
