### ISSUE TITLE
Camera in map view : ScaledSpace

### ISSUE THREAD

**Issue by EvilSanta** [krpc/krpc#339]
I was trying to figure out where the camera is positioned relative to a celestial body in meters but the distances used by PlanetariumCamera use ScaledSpace. The SpaceCenter service does not support a way to acquire the scale factor/transforms/conversion methods at the moment, it seems. It would be neat if this functionality was there.

**Comment by djungelorm** [comment]
I've changed it to return the camera distance in meters. Should fix your use case?

**Comment by EvilSanta** [comment]
I can work with this, yes. Thanks!
