### ISSUE TITLE
configure script for cpp client seems broken

### ISSUE THREAD

**Issue by SonnyJim** [krpc/krpc#343]
After a simple ./configure, make I get the following output:
`libtool: compile:  g++ -std=c++11 -DPACKAGE_NAME=\"krpc\" -DPACKAGE_TARNAME=\"krpc\" -DPACKAGE_VERSION=\"0.3.5\" "-DPACKAGE_STRING=\"krpc 0.3.5\"" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"krpc\" -DVERSION=\"0.3.5\" -DHAVE_CXX11=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -I. -I../include -I../include/krpc -g -O2 -MT platform.lo -MD -MP -MF .deps/platform.Tpo -c platform.cpp -o platform.o >/dev/null 2>&1
mv -f .deps/platform.Tpo .deps/platform.Plo
make[1]: *** No rule to make target 'service.cpp', needed by 'service.lo'.  Stop.
make[1]: Leaving directory '/home/pi/src/krpc-cpp-0.3.5/src'
Makefile:383: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
`

cmake seems to build fine, so it seems to be a problem with the configure script

**Comment by djungelorm** [comment]
Thanks for the bug report. There was a spurious file in one of the config files.
