### ISSUE TITLE
KSP 1.2 support

### ISSUE THREAD

**Issue by djungelorm** [krpc/krpc#345]

**Comment by hjfreyer** [comment]
Is there any way to run this against KSP 1.2 but without access to any of the new APIs?

**Comment by djungelorm** [comment]
Yep! Pre-release builds are available here:
http://krpc.s3-website-us-east-1.amazonaws.com/deploy/feature/ksp-1.2/

The latest release archive is:
https://krpc.s3.amazonaws.com/deploy/feature/ksp-1.2/688.1/krpc-0.3.6-19-gb523e0d.zip

**Comment by lpadukana** [comment]
Can't wait for this release! KSP 1.2 is out...

**Comment by djungelorm** [comment]
Here's an updated pre-release: https://krpc.s3.amazonaws.com/deploy/feature/ksp-1.2/708.1/krpc-0.3.6-46-gc1e39ed.zip

Bit closer to a full release, but I still have a bunch of failing test cases...

**Comment by djungelorm** [comment]
KSP 1.2 support is pretty solid now. Only remaining things on the todo list are:

* [ ] Find a fix or workaround for incorrect values returned by ModuleRCS.GetPotentialTorque
* [ ] Update and test InfernalRobitics when it supports KSP 1.2

Updated pre-release build: https://krpc.s3.amazonaws.com/deploy/feature/ksp-1.2/714.1/krpc-0.3.6-61-g0f6458a.zip

Note that I haven't added support for KerbNet. That'll come after v0.3.7.

**Comment by djungelorm** [comment]
Closing, as remaining issues are covered in #354, #366

Latest pre-release supporting 1.2.2 is here: https://krpc.s3.amazonaws.com/deploy/master/756.1/krpc-0.3.7-122-ge9f70cf.zip

v0.3.7 release is imminent... :)
