### ISSUE TITLE
Can't connect while game is paused

### ISSUE THREAD

**Issue by jazzpi** [krpc/krpc#347]
Not really sure if this is intended, but I just spent two hours debugging my firewall wondering why kRPC wouldn't respond :smile:

If this is intended, a (prominent) hint in the docs would be nice.

**Comment by djungelorm** [comment]
Sorry to hear that :(

The intended behaviour is to not receive and execute RPCs when the game is paused. But I hadn't considered the effect on connection attempts... which I think should be allowed when the game is paused. Especially if you have "auto-accept connections" enabled.

**Comment by djungelorm** [comment]
I've tried to get this working but it doesn't appear to be possible to get the Update() method to run when the game is paused. So the behaviour will have to stay as it is - however I will mention this clearly in the docs.

**Comment by djungelorm** [comment]
I've found a way to get the server to respond whilst the game is paused, and have decided to change to use this behaviour in the upcoming v0.4.0, as it would allow you to pause/resume the game from a client.
