### ISSUE TITLE
Expose GetPressure() and GetDensity() from KSP API.

### ISSUE THREAD

**Issue by JonasBM** [krpc/krpc#350]
Missing Scale height reference to the body, its important to calculate the dendity of air at given height.

**Comment by JonasBM** [comment]
Sorry, scale heigh is not a thing after 1.0.
Yet, theres no way to calculate without take the datá from the wiki.

**Comment by djungelorm** [comment]
I guess we need to add a method called `CelestialBody.AtmosphereDensityAt(altitude)`
(similar to [Flight.AtmosphereDensity](http://krpc.github.io/krpc/csharp/api/space-center/flight.html#property-KRPC.Client.Services.SpaceCenter.Flight.AtmosphereDensity) but with an altitude parameter)

Would that fix your use case?

**Comment by JonasBM** [comment]
That will help a lot, thanks.
CelestialBody.AtmospherePressureAt(altitude) would be nice too, but i can iterate and get the sum of densityAtAltitude * g * dh.
I'm trying to develop a console application to run remotely what is possible in KSP (if possible, will play a game only from the console).
After some study there's a lot missing for me to do exact what i wanted, cannot predict any drag or lift force, missing in special the DragCubeList Class, and its much to ask for now, meaby one day... ^^
I will try to get the drag and lift when in flight and store for each craft (like a experimental flight, more role play for me =D).

Thanks for this fantastic mod!

**Comment by djungelorm** [comment]
This has been mostly implemented but needs testing (changes are on branch feature/aero-sim).

I'm moving this to the 0.3.10 milestone so as to not delay a KSP 1.3.0 compatible release any longer.
