### ISSUE TITLE
Invalid vessel.available_rcs_torque

### ISSUE THREAD

**Issue by Assert1** [krpc/krpc#354]
For this vessel (placed directly into orbit):
[Test.craft.txt](https://github.com/krpc/krpc/files/504159/Test.craft.txt)

Mass: 54314.0
Inertia tensor (diagonal): 581216.3, 44035.9, 581252.8
Inverse of inertia tensor: 1.7205296392438620e-06, 2.2708731161259498e-05, 1.7204217829091489e-06

RSC torque computed by kRPC: 25136.576576232910, 15415.692382812500, 25137.642372131348 Nm

Product of inv tesnsor and torque (that is angular acceleration when this torque applied): 0.043248638011040313, 0.35007122168601973, 0.043247408710997789

But, actual angular acceleration (full control applied) measured with expiriments is: 0.011, 0.098, 0.011 rad/sec^2. That is 4x less than computed. May be you are using total thrust for each thruster to compute torque instead of thrust/thrusters_count.

**Comment by djungelorm** [comment]
FYI, RCS torque is computed by calling: ```ModuleRCS.GetPotentialTorque ()``` (kRPC doesn't use `thrust/thrusters_count` to compute it). Might be a KSP bug, I'll try and put together a workaround.

**Comment by djungelorm** [comment]
FYI, whilst upgrading the code for KSP 1.2 I've found that the values returned by 
`ModuleRCS.GetPotentialTorque` are incorrect. Not just a multiple of the true value, but totally random values that make no sense :( Rotating the vessel causes them to change drastically...

**Comment by djungelorm** [comment]
`ModuleRCS.GetPotentialTorque` is still bugged in KSP 1.2.2

**Comment by djungelorm** [comment]
Still broken in KSP 1.3.0, despite being reported on the Squad bug tracker for many months :(

**Comment by djungelorm** [comment]
http://bugs.kerbalspaceprogram.com/issues/15962

**Comment by djungelorm** [comment]
Was fixed in #552
