### ISSUE TITLE
No method to hide/show navball

### ISSUE THREAD

**Issue by cknowles2112** [krpc/krpc#355]
While there are methods to change views, open/close the map, zoom, etc - there does not appear to be a method to hide/show the navball.  (of course, this is mainly driven by the inconsistency in KSP itself, where the navball is hidden in map mode)

**Comment by cknowles2112** [comment]
With the advent of KSP 1.2 - there's now a setting to default the navball to visible in map view - so this may not be *needed* any longer, but more control is likely better than less.

**Comment by djungelorm** [comment]
I still think it's a worthy addition. Also, would be good to add showing/hiding the UI (pressing F2).
