### ISSUE TITLE
No Mention Of Dependincies

### ISSUE THREAD

**Issue by gudenau** [krpc/krpc#356]
It would be useful to show what Java dependencies are needed to use this Java client library.

**Comment by djungelorm** [comment]
This is documented here: http://krpc.github.io/krpc/java/client.html#using-the-library

Where did you look for the information? Maybe it is hard to find?

**Comment by gudenau** [comment]
Holy crap am I blind. Sorry. ._.

**Comment by djungelorm** [comment]
No worries :)
