### ISSUE TITLE
Stream API modifications.

### ISSUE THREAD

**Issue by Assert1** [krpc/krpc#358]
Adds a default contructor for stream to perform late initialization and\or store streams in structures (making list of engines propertys and keep it in sync with the vessel).

Simple use cases:

```
	kStreamF drag_coefficient_stream;
	kStreamF lift_coefficient_stream;
	kStreamF ballistic_coefficient_stream;
	kStreamF mach_stream;
	kStreamV lift_stream;
	kStreamV drag_stream;
	if(sc.far_available())
	{
		drag_coefficient_stream=flight_surf.drag_coefficient_stream();
		lift_coefficient_stream=flight_surf.lift_coefficient_stream();
		ballistic_coefficient_stream=flight_surf.ballistic_coefficient_stream();
	}
	else
	{
		mach_stream=flight_surf.mach_stream();
		lift_stream=flight_surf.lift_stream();
		drag_stream=flight_surf.drag_stream();
	};
```

```
	kStreamV target_position_stream;
	kStreamV target_velocity_stream;
	auto target_vessel=sc.target_vessel();
	auto target_body=sc.target_body();
	if(target_vessel._id)
	{
		auto target_frame=target_vessel.orbit().body().non_rotating_reference_frame();
		target_position_stream=target_vessel.position_stream(target_frame);
		target_velocity_stream=target_vessel.velocity_stream(target_frame);
	};
	if(target_body._id)
	{
		auto target_frame=target_body.orbit().body().non_rotating_reference_frame();
		target_position_stream=target_body.position_stream(target_frame);
		target_velocity_stream=target_body.velocity_stream(target_frame);
	};
```

Also, it is good idea to add bool operator for objects, or IsNULL method to test that it is non NULL.

**Comment by djungelorm** [comment]
This would also be useful for storing stream objects in standard library contains like std::vector.

I've added the following:
 * Default constructor
 * Copy constructor (which implicitly defines `operator=`)
 * `Stream::operator bool()` to check if the stream is set (i.e. the same as your IsNULL suggestion)
 * Updated the destructor to remove the stream from the server when all stream objects are destroyed. Implemented using a `std::shared_ptr` field in the stream object. Prevents early removal of the stream.

**Comment by Assert1** [comment]
nice, everything works fine, thank you!

**Comment by Assert1** [comment]
except google::protobuf::uint32 id; should be google::protobuf::uint64 id; at least to remove warnings.

**Comment by djungelorm** [comment]
Awesome! Annoyingly, they don't show up as warnings in gcc :(
