### ISSUE TITLE
KRPC.Client.Encoder not public

### ISSUE THREAD

**Issue by andyleap** [krpc/krpc#360]
I'm working on writing an extension, which seems to be relatively straightforward, but if I try to pass any parameters, the code generated for the CSharp client doesn't want to compile at all, complaining that `'Encoder' is inaccessible due to its protection level`.  I looks like KRPC.Client.Encoder has a bunch of public methods, but the class itself isn't given a protection level, and so defaults to private.  Any chance that could be changed?

**Comment by djungelorm** [comment]
Sure I'll make the class public.

**Comment by andyleap** [comment]
In addition, it appears the `RemoteObject` `connection` field, and the constructor, both need to be made public as well.
