### ISSUE TITLE
[Request] Contracts

### ISSUE THREAD

**Issue by nevercast** [krpc/krpc#361]
Hello,

I'd like to request support for Contracts, at the moment I personally would just like to spit out a list of Active contracts but presumably it makes sense to be able to fetch Active, Inactivate and Completed/Failed.

I'm not sure of the ins and outs of the Contract API so I wont be providing a PR for this.

Regards, NeverCast.

**Comment by djungelorm** [comment]
I've added the contracts API. Will be released with v0.3.8 hopefully in the next week or two.

It allows you to do all the things you requested, plus get all the rewards/penalties, and contract parameters.
