### ISSUE TITLE
Protobuf version

### ISSUE THREAD

**Issue by CryptoCopter** [krpc/krpc#362]
I was trying to build the c++ library, and it seems that I'm having an issue with the protbuf version.

The documentation simply states, that protobuf version 3 is required, so I built and installed the current release (3.1.0), but when I try building krpc 0.3.6, it tells me:

`#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer headers.  Please regenerate this file with a newer version of protoc.`

Is there an easy way to fix this or do I need to downgrade protobuf, and if that is necessary, to which version?

**Comment by djungelorm** [comment]
You need protobuf 3.0.0-beta-2.

I'm working on an update to use the reasonably recently released 3.0.0.

**Comment by CryptoCopter** [comment]
Thanks! Might be a good idea to put the exact version needed in the docs, considering that the abi is super volatile.
