### ISSUE TITLE
TestServer executables deployment

### ISSUE THREAD

**Issue by TeWu** [krpc/krpc#363]
As it turns out [kRPC-rb][2] requires a new version of [TestServer][3] for every kRPC server build it wants to be tested (compatible) with. This is a requirement that other third party clients may also have in future. For this reason I think it would be a good idea to deploy TestServer executables to [S3][1] during build process (on Travis CI).

From kRPC-rb point of view it would be best if this was separate zip file, containing only those files that are required to run TestServer (like those [here][4]).

[1]: http://krpc.s3-website-us-east-1.amazonaws.com/deploy/
[2]: https://github.com/TeWu/krpc-rb
[3]: https://github.com/krpc/krpc/tree/master/tools/TestServer
[4]: https://github.com/TeWu/krpc-rb/tree/ed42974b66160be2af83af0a1e78a9da6f6b356c/bin/TestServer

**Comment by djungelorm** [comment]
Travis now outputs the required zip file. For example, for the latest v0.4.0 build:
https://krpc.s3.amazonaws.com/deploy/v0.4.0/745.1/TestServer-0.4.0-182-g2eb7987.zip

PS. Sorry for the delay on this, been rather busy lately...

**Comment by TeWu** [comment]
Thanks for the TestServer files.
I can run it locally just fine, but apparently Travis can't, as you can see [here][1] (It's the latest build of krpc-rb [proto_change_0.4|new_test_server][2] branch which is using [shell script][3] to download TestServer executables from [here][4]). I'm not sure how to deal with this issue and wonder if you could help?

[1]: https://travis-ci.org/TeWu/krpc-rb/builds/183717311
[2]: https://github.com/TeWu/krpc-rb/tree/proto_change_0.4%7Cnew_test_server
[3]: https://github.com/TeWu/krpc-rb/blob/proto_change_0.4%7Cnew_test_server/bin/download_test_sever.sh
[4]: https://github.com/TeWu/krpc-TestServer/releases/tag/0.4.0-182-g2eb7987

**Comment by djungelorm** [comment]
I've managed to reproduce the exception locally, within a docker container. Will try and find a fix!

**Comment by djungelorm** [comment]
Aha! You're using an old version of mono. You need to add the "mono" source to your .travis.yml so that it installs from the mono project repository:

```
addons:
  apt:
    sources:
      - mono
    packages:
      - mono-devel
```

**Comment by TeWu** [comment]
That make sense, and more importantly fixes this issue.
Thanks a ton!
