### ISSUE TITLE
Invalid DockingPort.rotation?

### ISSUE THREAD

**Issue by Assert1** [krpc/krpc#371]
I am expected that:
DockingPort.rotation(target_frame)
should be queal to:
sc.transform_rotation(Q(0.0, 0.0, 0.0, 1.0), DockingPort.reference_frame(), target_frame)
First line resturn some very strange things... i do not know what is this and how to use it. Second line works fine as workaround for me, but... it shoul be equal, no?

**Comment by djungelorm** [comment]
It is indeed a bug, I've committed fixes for both DockingPort.Rotation and Part.Rotation, which were applying the world -> reference frame transformation incorrectly. Thanks!
