### ISSUE TITLE
Problems with maneuver node removing...

### ISSUE THREAD

**Issue by Assert1** [krpc/krpc#372]
![bandicam 2016-12-28 15-43-04-264](https://cloud.githubusercontent.com/assets/17066188/21520208/7f6418bc-cd14-11e6-841c-f6ed07f024d4.jpg)
![bandicam 2016-12-28 15-43-09-427](https://cloud.githubusercontent.com/assets/17066188/21520209/7f654566-cd14-11e6-832b-45dec37edb26.jpg)
Node sprite stays on the screen after deletion, 
Also, i have an exception [libprotobuf FATAL g:\projects\ksp\external\protobuf\include\google\protobuf\repeated_field.h:1431] CHECK failed: (index) < (current_size_): thrown somewhere... same code works fine for kRPC 0.3.6 and KSP 1.1.3.

**Comment by Assert1** [comment]
![bandicam 2016-12-28 15-50-49-339](https://cloud.githubusercontent.com/assets/17066188/21520335/7c06bc64-cd15-11e6-811a-5f82f3cbf7ce.jpg)

**Comment by djungelorm** [comment]
I've managed to get the sprite to appear - so will look into how to fix it.

Can you give more details on what the exception was? Do you have a stack trace?

**Comment by Assert1** [comment]
Can't intercept this exception simply:( I think it is rised because of some streams are linked to manuver node that is deleted. But deletion itself that is:
	auto nodes=Control->nodes();
	for(auto node : nodes)node.remove();
Works without exceptions... also, i am deleting 2 nodes, and only second sprite will stay after this. May be some internal indexing is wrong after first node.remove, and other node indexes became invalid...

**Comment by Assert1** [comment]
I am really do not know what is wrong there, may be you can trace on your side... this is my maneuver computation utility and instruction of how to use it.

[ManeuverControl.zip](https://github.com/krpc/krpc/files/785746/ManeuverControl.zip)

**Comment by djungelorm** [comment]
Thanks! I managed to reproduce the issue a while back, but was unsuccessful in finding what was causing it as the KSP API is basically undocumented, so using it is mainly guesswork. Will have another look and see if I can find a fix.

**Comment by djungelorm** [comment]
I think I've fixed it :) Here's a build for you to try:
https://krpc.s3.amazonaws.com/deploy/bug/maneuver-nodes/831.1/krpc-0.3.8-70-gd40d497.zip

Could you let me know if that helps? I can't run your maneuver control program as I'm on Linux, but I did test it this script which reproduced the problem and now works with the new version: d40d497af649e661ef088094ef383b42e00c549c

**Comment by Assert1** [comment]
yep, fixed. Thank you.
