### ISSUE TITLE
"Not the active vessel" RPCException after activating a stage with a decoupler

### ISSUE THREAD

**Issue by kenny-evitt** [krpc/krpc#380]
I'm running code in LINQPad on Windows 10 and I ran into the above-described exception.

Exception details:

```
Message	Not the active vessel
Data	Data
InnerException	null
TargetSite	TargetSite
StackTrace	   at KRPC.Client.Connection.Invoke(Request request)
   at KRPC.Client.Connection.Invoke(String service, String procedure, IList`1 arguments)
   at KRPC.Client.Services.SpaceCenter.Control.ActivateNextStage()
   at UserQuery.FlyTest5(Connection connection, Vessel test5) in C:\Users\kenny\AppData\Local\Temp\LINQPad5\_vljpsxrx\query_ofzogd.cs:line 139
   at UserQuery.Main() in C:\Users\kenny\AppData\Local\Temp\LINQPad5\_vljpsxrx\query_ofzogd.cs:line 54
   at LINQPad.ExecutionModel.ClrQueryRunner.Run()
   at LINQPad.ExecutionModel.Server.RunQuery(QueryRunner runner)
   at LINQPad.ExecutionModel.Server.StartQuery(QueryRunner runner)
   at LINQPad.ExecutionModel.Server.<>c__DisplayClass152_0.<ExecuteClrQuery>b__0()
   at LINQPad.ExecutionModel.Server.SingleThreadExecuter.Work()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
HelpLink	null
Source	KRPC.Client
HResult	-2146233088
```

The line of my code where the exception was thrown:

```
test5.Control.ActivateNextStage();
```

`test5` is a `Vessel` object created by this line:

```
	using (Connection connection = new Connection("abc"))
	{
		KRPC.Client.Services.KRPC.Service krpcService = connection.KRPC();
		KRPC.Client.Services.SpaceCenter.Service spaceCenter = connection.SpaceCenter();
		Vessel vessel = spaceCenter.ActiveVessel;
		...
```

**Comment by kenny-evitt** [comment]
Here's [the relevant kRPC code](https://github.com/krpc/krpc/blob/6ba67164b99813e0a7be32533ada9fc7d9cae222/service/SpaceCenter/src/Services/Control.cs#L410-L414):

```
        void CheckActiveVessel ()
        {
            if (vesselId != FlightGlobals.ActiveVessel.id)
                throw new InvalidOperationException ("Not the active vessel");
        }
```

I added some 'print statements' to my code:

```
	String.Format("The ID of the active vessel is {0} and its name is \"{1}\".", spaceCenter.ActiveVessel.id, spaceCenter.ActiveVessel.Name).Dump();
	String.Format("The ID of the original vessel object is {0}.", test5.id).Dump();
```

and confirmed that indeed the IDs of the currently active vessel and `test5` are different.

I notice that `ActivateNextStage` returns a collection of vessel objects and that the API docs state that it returns "A list of vessel objects that are jettisoned from the active vessel.".

What seems to be failing for me is retaining and using a single `Vessel` object referencing the vessel as of when I first called `spaceCenter.ActiveVessel`. But jettisoning parts results in a new vessel becoming the currently active vessel.

What's the best practice, or at least some good patterns, for maintaining a reference to a single vessel over extended periods of time?

**Comment by kenny-evitt** [comment]
The exception is thrown even if I do _not_ switch the Windows app focus from KSP while my code is running.

**Comment by djungelorm** [comment]
In my programs, I make sure to get a fresh vessel object by calling SpaceCenter.ActiveVessel whenever performing an operation that might change the active vessel.

I admit this is a bit clunky, but it's currently the only way - as you have figured out the vessel object is simply a container for a vessel id.

Maybe we should extend the API to add a special sort of Vessel object that always refers to the active vessel, that way the client does not need to worry about it changing.

**Comment by kenny-evitt** [comment]
@djungelorm Is this how KSP works itself? I.e. is there no 'ship' object that stays unchanged between changes to the 'vessels'?

I'm thinking of just encapsulating the logic of re-acquiring a reference to the current vessel whenever necessary, e.g. after staging that decouples parts. I figured that it would be useful to retain references to a specific ship so that the code could handle multiple ships (tho one at a time).

> Maybe we should extend the API to add a special sort of Vessel object that always refers to the active vessel, that way the client does not need to worry about it changing.

Don't do this on my behalf. I think I'm fine with my workaround outlined above.

Want me to close this issue?

**Comment by djungelorm** [comment]
Leave it open for now, I'll at least update the documentation to make the behaviour a bit clearer.

**Comment by djungelorm** [comment]
And yes, that is how KSP works itself. There is no ship object that's left unchanged. There's just an active vessel reference in flight globals that gets updated.
