### ISSUE TITLE
Add example for landing reference frame to the documentation

### ISSUE THREAD

**Issue by janismac** [krpc/krpc#381]
For writing landing autopilots it is useful to have a reference frame with the origin at the landing site and Up-North-East orientation.

I spent some time trying to get this right: https://gist.github.com/janismac/1c206dfa859e008bafcfe3bc6fcb1b0e

To spare others the effort, maybe you could add it to the documentation here: http://krpc.github.io/krpc/tutorials/reference-frames.html#angle-of-attack

Screenshot of the script in action:  
![vab](https://cloud.githubusercontent.com/assets/2456759/24074806/08e0c010-0c10-11e7-94a2-5efb37100f5e.jpg)

EDIT: After some more testing I discovered the velocity is wrong, `vessel.velocity(landing_reference_frame)` shows the planets rotation speed for a vehicle that is at rest on the surface. Though I'm not sure how to correct that.

**Comment by djungelorm** [comment]
Thanks for the example code! Will get back to you on the velocity issue when I have time.

**Comment by djungelorm** [comment]
I found a bug that explains the velocity problem. A fix will be released in v0.3.8 in the next week or so.
