### ISSUE TITLE
SAS seems to overwrite Vessel.Control.{yaw,pitch,roll}

### ISSUE THREAD

**Issue by mkluge** [krpc/krpc#384]
If I have a vessel where the SAS has really to work hard to keep it stable, it seems that input that I give via Vessel.Control.{yaw,pitch,roll} is ignored. Especially when the vessel is not in space yet. I can then set values and see no movement/deflection in the needles in the lower left part of the KSP screen. But when I press the WASD keys, it works. Is this behavior expected, normal or can this be avoided? O am I doing something wrong? Autopilot is turned off, only SAS is on. I am using python and write to Vessel.Control.... 
Once the vessel is in space and the SAS has not do do heavy corrections, everything works well. If you need more information or if I can help with more test, I can do this.

**Comment by cknowles2112** [comment]
Can confirm this concern.  (might be intentional behavior - but it's unclear - the docs say that setting pitch/yaw/roll is intended to be just like hitting and holding the corresponding key)

This appears to happen even without needing to "really work to keep stable".

If I have a kerbalX in orbit, and I leave SAS off, and set pitch to 1 for 3 seconds,  the craft does almost precisely 150deg.  then I turn sas on, wait for things to stabilize, and set pitch to -1 for 3 seconds.  The craft only describes about 45deg.  Though it's much more "controllable" by using the sas - it's also much slower.  

Just using the keyboard controls shows a behavior very much like that of the SAS off version.

Also can confirm that the pitch/roll/yaw indicators show an initial "twitch" as the command starts, but then get very close to zero.

**Comment by Janikiii** [comment]
EMAIL RECEIVING DENIED


Am 27.03.2017 um 21:59 schrieb Chris Knowles:

**Comment by djungelorm** [comment]
This is actually intended behaviour, although poorly documented - apologies! Also, this behaviour is potentially badly thought through on my part...

What is happening is that the inputs from the control class are *added* to the SAS controls. So, for example, if SAS is setting a pitch of +1 and the control class sets a pitch of -1 the overall pitch control will be 0.

The keyboard controls *overwrite* the controls set by SAS. So, for example, if SAS is setting a pitch of +1 and the S key is pressed, the overall pitch control is -1 (not 0 as with the control class).

I forget what the specific use case was for this behaviour as it was implemented a long time ago, but I'm open to arguments that using the overriding approach would be better. Could also add the ability to choose which behaviour you want, if that's useful?

**Comment by mkluge** [comment]
Well, one explanation of why you implemented it this way is the assumption, that external controllers/scripts would continuously send values. Thus, they will send a lot of zeros if joysticks are not touched. So, adding makes a lot of sense. I would propose a factor that can be set that gives the internal SAS control a weight, relative to the krpc controls. So I can temporarily overwrite SAS on demand. What the code does at the moment is:

sas = ksp_internal + krpc_control

What I propose is:

internal_sas_factor = 0.1
sas = ((ksp_internal * internal_sas_factor) + krpc_control ) / (1+internal_sas_factor)

The default for the internal_sas_factor (which can be read and written) would be 1. This way current designs would not be broken, but I can set it on demand to 0 and and back to 1 if I see input from my joystick. Without the need to deactivate and re-activate SAS.

**Comment by cknowles2112** [comment]
So, in one of my tests, I set the script to continuously send the 1, and didn't see any increase in responsiveness of hte vessel.  So, I don't think that's what's happening.

As to documentation - the krpc docs (which are actually pretty impressively well done) state that the yaw/pitch/roll are "equivalent" to pressing the keys - hence the expectation that that is what would happen.

I'd vote for either just making the krpc fed value *the* value - like pressing the keys, or, slightly less so from my perspective, but still totally valid, the ability to feed in a flag "no, really, do THIS" vs "just add my input to your internal stuff." (which seems to be the current setup if I'm understanding.)

**Comment by mkluge** [comment]
Sounds valid. The difference between key presses and script/joystick input is that keys are released after some time and SAS can take control back. So what might be needed is something like disabling SAS while feeding values to krpc.control... ? For joysticks I would like to have the behavior that I don't have to disable SAS for the moments when there are values!=0 from the joystick that are feed to krpc. At the moment I think I could do this as a workaround and it would actually work.

**Comment by cknowles2112** [comment]
Certainly that's possible, but it's a bit kludgey - and it is a bit more state to track in the code, while changing krpc controls to replacing values instead of adding them, a) matches the documentation and b) expectation - if I set the yaw/pitch/roll to something, stands to reason that I'm *setting* the yaw/pitch/roll to that.  (and if you really want to do additive, you can set control.yaw = control.yaw
 + additiveyaw )

**Comment by djungelorm** [comment]
> So, in one of my tests, I set the script to continuously send the 1, and didn't see any increase in responsiveness of the vessel. So, I don't think that's what's happening.

Setting the property repeatedly won't have any effect! It will just update the value used by the server in the game loop, setting it to the same value, hence no change.

**Comment by djungelorm** [comment]
I thought it would be good to clear a few things up, as the documentation is very lacking. The current way it works is as follows:

 * Each vessel has three control sources:
   1. The stock game (i.e. key presses and SAS)
   2. kRPC's Control class
   3. kRPC's AutoPilot class
 * There is one instance of the Control and AutoPilot class per vessel.
 * Note that there is *not* a Control/AutoPilot class per client. Each client shares the same instance of these classes.
 * The pitch/roll/yaw values that the vessel uses are computed by taking the pitch/yaw/roll values set by the stock game, adding the values from the Control class, and then adding the values from the AutoPilot class (if it is enabled).
 * This calculation is done once per game tick.

Here's some pseudo-code that summarises this:
```python
def compute_pyr_on_game_tick(vessel):
    pyr = stock_game.get_pyr(vessel)
    pyr += vessel.control.get_pyr()
    if vessel.autopilot.enabled:
        pyr += vessel.autopilot.get_pyr()
    return pyr
```

The code that implements this can be found here: https://github.com/krpc/krpc/blob/master/service/SpaceCenter/src/PilotAddon.cs#L258

----

The issues highlighted in the OP boil down to wanting the Control class to behave exactly like the keyboard.

The simplest way to allow this use case is to add a boolean flag to control whether the values from the Control class are added to, or override, the values set by the stock game.

The algorithm can be amended as follows to do this:
```python
def compute_pyr_on_game_tick(vessel):
    pyr = stock_game.get_pyr(vessel)
    if vessel.control.override:
        pyr += vessel.control.get_pyr()
    else:
        pyr = vessel.control.get_pyr()
    if vessel.autopilot.enabled:
        pyr += vessel.autopilot.get_pyr()
    return pyr
```

I don't think we need anything more complex than this.

**Comment by cknowles2112** [comment]
I think that would be fine.  Flexibility is a good thing.

**Comment by mkluge** [comment]
Sounds good to me.

**Comment by djungelorm** [comment]
I've made these changes, and will release them in the next version.
Sorry this took me so long to do! It somehow slipped off my todo list...
