### ISSUE TITLE
Add VesselType for relay and plane

### ISSUE THREAD

**Issue by 10bag** [krpc/krpc#385]
As far as I can tell, KRPC 0.3.8 does not recognise the relay or plane vessel types.

E.g: create or re-classify a craft as a relay satellite or plane, then check it's vessel.type using KRPC. Shouldn't it be expected to return something like VesselType.relay or VesselType.plane?

I'm both a Python and KRPC noob so pardon any lack of details or understanding.

**Comment by djungelorm** [comment]
Yeah they're missing, need to be add them to the VesselType class.
