### ISSUE TITLE
c# client on linux slow over wi-fi

### ISSUE THREAD

**Issue by Tunefix** [krpc/krpc#387]
When running the c# client on linux (Ubuntu 16.04.2) over wi-fi connection RPC-calls are slow.
If running the same client with cable (on same computer) it is much faster.

Slight correction: it is slow in any OS over wi-fi, probably because the requests don't arrive fast enough.
I believe the solution is to use streams, but streams don't seem to work in Ubuntu. (Program freezes on stream.Get()-command)

Any idea what can cause this?

**Comment by djungelorm** [comment]
The RPC execution rate is mainly affected by the latency of the network, so I guess the latency over WiFi is much higher than over your wired network.

If all you are doing is fetching telemetry repeatedly, then yes streams would help. They should work on Ubuntu. 16.04 is used to run the tests, so should work. Maybe you are using them incorrectly? Could you post some example code that demonstrates the freeze and I'll see if I can help?

**Comment by Tunefix** [comment]
I activate streams like this:
flight_stream = connection.AddStream(() => spaceCenter.ActiveVessel.Flight(flightRef));
flight = flight_stream.Get();

The first line is executed with no problems, then is freezes.
( I will look at your test-code to see if it is just me beeing an idiot. :-p)

**Comment by Tunefix** [comment]
Looks like this is a compiler issue on my end. I Guess xbuild are compiling with .net 4.6, and then mono are executing with .net 4.5, causing missingMethod exception.

**Comment by djungelorm** [comment]
Aha, glad you found the cause!
