### ISSUE TITLE
Target switching locked

### ISSUE THREAD

**Issue by artwhaley** [krpc/krpc#397]
Hey there!  Sorry to randomly disappear for so long, but I'm back around and will pitch in as I can.  I have either found a bug or a feature, I'm not sure which.   I'm playing in a new sandbox save, and when trying to use KRPC to set a target, either vessel or docking port, no error is shown in the python window, but KSP displays the text 'Target switching locked' and the target is NOT changed.  The only reference I found to this message was a forum post with someone asking if they had their space center upgraded....  so it may be something to do with that?   The python code I was trying - 

for idx, vessel in enumerate(conn.space_center.vessels):
    test=str(vessel.name)
    if test == 'ISS Command/Utilities':
        sc.target_vessel=vessel
        print("target acquired")
		
		
for p in conn.space_center.target_vessel.parts.docking_ports:  #Set Target Port
    for m in p.part.modules:
        if m.has_field("Port Name"):
            if m.get_field("Port Name")=="hab":
                conn.space_center.target_docking_port=p

**Comment by artwhaley** [comment]
So...  did a bit of research and found where KOS had chased the same problem a bit.  As per usual, I'm in over my head -   but running InputLockManager.ClearControlLocks();  DOES clear the control lock and allow a target to be set, though I have no idea what ELSE I'm interfering with.  My limited efforts to figure out how to get KSP to actually give me a list of what control locks were in effect failed, so I can't figure out what is setting the control lock.

I have removed every mod except KRPC and Mechjeb and as far as I can tell with github's search - the only input lock in mechjeb's code is during mouseover their windows (And we might need to ask them to exclude target setting from that input lock, to avoid bugs if you happen to have your mouse over their window?)

**Comment by artwhaley** [comment]
I figured out what was causing this for me - the application locks a set of inputs whenever the KSP window loses focus and this includes the targeting control lock..   flightDriver_ApplicationFocus is the lock handle under that circumstance.  I'm going to WAGER this means that setting targets might fail if the mouse is over a dialog box... either stock ui or mod...  etc.  

It seems that we could add something like -  

 InputLockManager.lockMask &= (ulong) ~ ControlTypes.TARGETING;
just before the target is set and 
InputLockManager.lockMask &= (ulong)ControlTypes.TARGETING;
after it into all the set { }'s on the  target properties and it would just work?  I don't have a local copy of KRPC at the moment and I'm not sure this is the smartest of all possible fixes to the problem so I won't make a PR right now...  but I did toss those two lines of code into a test KRPCService here and loaded it up and it seemed to work?

**Comment by djungelorm** [comment]
Sorry been a bit busy recently and not had any time to look at this. Thanks for finding all this out!

I've not come across this before, so I'm also not sure what other effects clearing the flags will have. When I have some time I could make the changes you suggest and run all the unit test to see if it affects anything else.

I think we should at least throw an exception from the set target RPC to the client if the call fails to set a target. And do the same for any other control locks we can find.

Also, what do you mean by the KSP window? Do you mean when the game is running in window mode and you alt+tab or click out of the game?

**Comment by artwhaley** [comment]
Yes, that's what I meant by the KSP window.   When the application loses focus it sets those locks.  I also discovered that in the Alt-F12 debug window of KSP there's a field to view current locks, so you can view the bitmask in real time as you move the mouse around.   I didn't find that hovering over either THAT window or a Mechjeb window, both of which set control locks when you mouse over, locked out target setting, but it was late at night and I wasn't doing indepth testing.  I came up with something else I wanted to fiddle with too... so I'm throwing linux in a virtual machine so I can get back to hacking at things, so I'll test this out a bit on my fork and keep you updated!  

I hope it's the good kind of bit busy and not the bad lately!

**Comment by djungelorm** [comment]
I've been poking around with this a bit more, and now understand the control locks more fully.

Then I stumbled upon the optional second argument to FlightGlobals.fetch.SetVesselTarget which is a boolean that lets you override target locks! So fixing this behaviour should be as simple as passing true for this argument.

**Comment by djungelorm** [comment]
Removed from the 0.3.9 milestone, as this is technically fixed. But leaving this as a reminder to check if input locks affect any other functionality.

**Comment by djungelorm** [comment]
Not noticed any other issues with this, so closing.
