### ISSUE TITLE
Support KSP 1.3 in CKAN package?

### ISSUE THREAD

**Issue by kenny-evitt** [krpc/krpc#400]
The kRPC mod listing in CKAN indicates that it isn't compatible with KSP 1.3.

**Comment by artwhaley** [comment]
Djungelorm has been way busy the last few weeks.  There doesn't seem to be much that needs to be done other than updating the dialog box calls...  I've got a seemingly fixed build compiling... I'm not smart enough to get the whole project to build and test though so don't want to try to make those changes without some input from him.    So...  thank you for checking in!  Djungelorm, if i can be of help let me know... but I THINK you'll be able to fix it and push an update out faster than you can talk me through the process.

**Comment by djungelorm** [comment]
Got some time this week to work on this :)

I had a go at compiling for the 1.2.9 pre-release a few weeks back, and also found that the only things that needed to be changed were calls to popupdialog. Hopefully with those changes I can run the automated tests and nothing else will be broken!

**Comment by djungelorm** [comment]
Released! :)

**Comment by kenny-evitt** [comment]
Awesome! Thanks!
