### ISSUE TITLE
Add a bind option to TestServer 

### ISSUE THREAD

**Issue by evanova** [krpc/krpc#402]
As a tester, I would like to be able to choose the bind address of the TestServer so that it is reachable from any machine on the same network and not just locally.

The current TestServer uses the loopback address (127.0.0.1) as the address to bind to. This prevents clients from connecting to it from a remote machine even if it's on the same network. For instance, my test server runs on the machine known as "192.168.1.4" but binds to "127.0.0.1" instead. I then cannot reach it from a different machine using "192.168.1.4" as the server is not bound to that address.

The attached file is a modified version of TestServer/Program.cs. It introduces a --bind option which defaults to 127.0.0.1 and solves the issue.

Sorry I did not create a fork since I could not get the whole solution to compile and run in a timely manner. The change is however trivial as you will see.
[Program.cs.txt](https://github.com/krpc/krpc/files/1058250/Program.cs.txt)

**Comment by djungelorm** [comment]
I've added your changes, and some checking that the argument passed to --bind is a valid address.

A pre-release build is available here if you want to try it: http://krpc.s3-website-us-east-1.amazonaws.com/deploy/master/907.1/

Thanks!

**Comment by evanova** [comment]
Tested. Works like a charm. 
Thanks for the quick addition.
