### ISSUE TITLE
Launch Into Orbit tutorial wrong staging number for SRB resources

### ISSUE THREAD

**Issue by Ramh5** [krpc/krpc#403]
I don't know if I am the only one that tried the tutorials in a while but I noticed a typo that makes the SRBs stages just after launch. 

I fixed it by using stage 2 instead of stage 3 in `vessel.resourcesInDecoupleStage(3, false);`
And it seems to make sense according to the documentation that the SRBs are indeed decoupled in stage 2 and asking resources for parts that are decoupled in stage 3 gives zero which makes the SRBs decouple at launch.

I used the downloadable craft file and Java code:

![screenshot0](https://user-images.githubusercontent.com/16180873/26893056-759d5992-4b77-11e7-9f61-4a70e1780055.png)

**Comment by djungelorm** [comment]
Confirmed, should be stage 2. Thanks!
