### ISSUE TITLE
node.reference_frame not updating?

### ISSUE THREAD

**Issue by artwhaley** [krpc/krpc#404]
I was attempting to write a node execution script and found that while 

vessel.auto_pilot.reference_frame = node.reference_frame
vessel.auto_pilot.target_direction = (0, 1, 0)

does exactly what it should, as the burn progresses this does not 'track' the node's remaining burn vector so if the burn isn't perfect and the heading to the node shifts, you end up finishing the burn on the wrong direction?    Is this an intended behavior with an obvious work-around to stay pointed at the current burn vector that I'm just missing?   or something that should be updated?

**Comment by artwhaley** [comment]
Found workaround with ap.target_direction =node.remaining_burn_vector .  Should the launch into orbit script be updated to include repeating that statement in a loop, as a more 'fault tolerant' example of how to execute a burn?  Or should the node.reference_frame update to the current node heading anyway?

**Comment by djungelorm** [comment]
Sounds like a bug to me. I think the intended behavior was for the reference frame to point in the remaining burn vector direction. Will investigate.

**Comment by djungelorm** [comment]
I think that change fixes the issue. I haven't had a chance to test it yet though.

**Comment by djungelorm** [comment]
On further reflection, I think it best if we add an additional reference frame, called `Node.remaining_burn_reference_frame` and leave `Node.reference_frame` as it currently is. I can envisage use cases for both being useful.
