### ISSUE TITLE
Autopilot Oscillates to and from Vertical Orientation

### ISSUE THREAD

**Issue by BenChung** [krpc/krpc#406]
I'm working on a landing autopilot, and have experienced an odd issue with the AutoPilot whereby the vehicle will oscillate between the vertical (body-normal) orientation and the commanded orientation.

For an example of its effects on my code, see the following video, starting at around the 35s mark: 

https://www.youtube.com/watch?v=6plXQEpTGww

The short white line is the commanded thrust direction, which can be easily compared with the real orientation of the vessel. This particular flight then gives rise to the following error plot:

http://i.imgur.com/bjDuo3S.png

Where the Y-axis is in degrees error, and the X-axis is in seconds post-guidance initialization.

Additionally, the behaviour can be replicated simply. Using the Python API,

```
import krpc
import numpy as np
import numbers
import time
from math import sin, cos, pi

class PyDriver:
	def fly(self):
		conn = krpc.connect(name="ConvexLand")
		sc = conn.space_center
		vessel = sc.active_vessel
		ap = vessel.auto_pilot
		rframe = vessel.surface_reference_frame
		flight = vessel.flight(rframe)
		utstream = conn.add_stream(getattr, sc, 'ut')
		start = utstream()
		ap.engage()
		while True:
			elapsed = utstream() - start
			scaled = elapsed * 1.0 # degrees per second
			degrees = scaled % 360
			x_dir = sin(degrees * pi/180.0)
			y_dir = cos(degrees * pi/180.0)
			z_dir = 0
			ap.target_direction = (x_dir,y_dir,z_dir)
			time.sleep(1.0/30.0)

PyDriver().fly()
```

This program should result in a smooth flip of the vehicle. However, if ran, the system will exhibit the extremely unusual instability, which is typically exhibited when the script is initially started, or when the real rotation is perturbed by human input substantially.

**Comment by artwhaley** [comment]
I hate to say it... but I was unable to reproduce the bug.   The code ran smoothly on a test vehicle for me...   nice slow smooth flip...  a quick roll to correct when it overflowed... but...  the actual flip was nice and steady.  I restarted the script several times and wiggled the control inputs myself.   

That said... I was having some weird times with the autopilot myself the other day... and will be spending some time with it this weekend.  I'll sure keep an eye on it.  Is there... ANYTHING else that could be interfering?

**Comment by djungelorm** [comment]
Maybe it's also dependent on the vessel? The autopilot does auto tune itself based on the characteristics of the vessel involved. Could you post a craft that experiences the issue?

**Comment by BenChung** [comment]
@artwhaley Thanks - I went through all my mods and found the issue. It's being created by an interaction between TCA and KRPC, though I have no idea what that interaction could be. Just turning TCA off in-game is enough to prevent it.

@djungelorm Sorry for the trouble, I should have checked all my control mods first.

**Comment by djungelorm** [comment]
No worries. I'm happy to look into the mod interaction though if you like.

**Comment by BenChung** [comment]
It isn't really required - I haven't been using TCA much in any case. If you don't have anything else to do, then it may be worth looking into, but it's not high priority.

On another topic, [my landing autopilot works much better now](https://www.youtube.com/watch?v=8-B9xKSB-d4)
