### ISSUE TITLE
C# Parachutes: RPCException

### ISSUE THREAD

**Issue by eugene-prout** [krpc/krpc#411]
I have the following snippet in my code:
```
foreach (Parachute para in vessel.Parts.Parachutes)
{
    para.Deploy();
}
```
A small section used to deploy all of the parachutes on the active vessel. However, when I run the code a "KRPC.Client.RPCException" is thrown. 
What is causing this error, and how can I prevent it?

**Comment by artwhaley** [comment]
Is it providing any explanation along with the exception as to what the issue is specifically?   Also, as a work around - can you set vessel.control.parachutes to true?

**Comment by eugene-prout** [comment]
No, it is just the RPCException with no other details... The work around does the same job and is more straight-forward so I think I will use that instead.

Thanks for the help.
