### ISSUE TITLE
Add method or methods to get Latitude and Longitude and altitude FROM a position in a reference frame?

### ISSUE THREAD

**Issue by artwhaley** [krpc/krpc#412]
This is an easy one I'm happy to hit myself, but wanted to get your opinion on how you'd like it done before I hacked around.   

It seems that the celestial body class in the space center service should have a method or methods to get the latitude and longitude from a position?  The reverse already exists.   

The API has handy methods for getting this exposed, so my only real question is:

Would you prefer ONE method that returned a list or tuple3 of latitude, longitude, altitude? 

OR
TWO methods - one that returned altitude and another that returned a list or Tuple of latitude and longitude?

OR
Three separate methods as inlatitude_from_position, longitude_from_position, and altitude_from_position ?

**Comment by artwhaley** [comment]
After a bit of thought, I think I figured out what you'll say.  lol.   All of the RPCs for grabbing the Lat and Lon and Altitude of a vessel are individual, so it makes sense to keep doing it that way.   This improves clarity as there's no need to figure out what the two or three parts of a returned list or tuple are!   

If that guess ISN'T right, let me know and I'll redo it, but going to take a hack at doing it that way.

**Comment by artwhaley** [comment]
Added PR 413 to address this.  https://github.com/krpc/krpc/pull/413

**Comment by djungelorm** [comment]
Thanks for the changes. Sorry it took me so long to look at this! I've merged the pull request.
