### ISSUE TITLE
v0.4.0 unable to connect to websocket server if connection keep-alive is set

### ISSUE THREAD

**Issue by lucaelin** [krpc/krpc#418]
When connecting to krpc v0.4.0 using Firefox (WebSocket), the server responds with a 400 Bad Request. This is because the `connection` header is rejected on the server for not being `upgrade`. The client actually sends `keep-alive, upgrade`, but the server does not check for this.

**Comment by djungelorm** [comment]
Thanks, I'll look into it. The header processing is rather basic so I'm not surprised this broke!

**Comment by djungelorm** [comment]
Should now be fixed on the v0.4.0 branch.
