### ISSUE TITLE
Ability to Pause game using krpc

### ISSUE THREAD

**Issue by cknowles2112** [krpc/krpc#422]
I'm building a simpit, and the only function I've not found in krpc that would be helpful is a pause function.  

While I'm aware that pausing is a function you can attach to an alarm, my tests show that setting instantaneous alarms doesn't quite work as expected.  So a straightforward pause function would be awesome.

**Comment by djungelorm** [comment]
Do you mean pause the game entirely? Our pause your client program until some event occurs? If you mean the latter, that's coming in v0.4.0 :)

**Comment by cknowles2112** [comment]
Yes, that is confusing.

My desire is to pause the entire game, though pausing the client until
events will be very useful.

**Comment by djungelorm** [comment]
This is related to #347

**Comment by djungelorm** [comment]
I've implemented this for v0.4.0. For example:
```
import krpc
conn = krpc.connect()
conn.krpc.paused = True
```
