### ISSUE TITLE
Initial connect times out in krpc4.0 

### ISSUE THREAD

**Issue by cknowles2112** [krpc/krpc#425]
If I run the python code: 
import krpc
conn = krpc.connect(name="test")

Before I can switch context and click on "Allow" the code times out with an error:

krpc.error.ConnectionError: The operation has timed-out.

Previous to 4.0, I was able to wait nigh unto forever, and click allow in ksp, and all would be well.

If I change the server to auto accept, things work, but this appears to be a change in behavior that isn't in the docs.

**Comment by mathuin** [comment]
This appears to be a feature, based on the changelog for 0.4.0.

Under the "Python client" section, there is the following line:  "Remove connection retries. Client will now fail fast if it fails to connect to the server".  

I suspect that the pre-0.4.0 code had retries which allowed you to switch context and permit the connection to the server.

**Comment by cknowles2112** [comment]
Hrm.  Me-- for not checking the changelog.

I see that this same change was made in the other languages as well, so it's not just python.

However, this is still a change in behavior from what the docs state.  The behavior seems to be "fail after ~1 second" - which makes the manual approve/deny of connections near impossible.  So, either drop that too, and default to auto accept connections, or ... something else.

I *am* able to work here, this is just a "there's now a mismatch between docs, expected behavior, and existing behavior" This issue isn't critical, it's just a change that can break existing practice.

**Comment by djungelorm** [comment]
This is a bug - the behavior is supposed to be the same as the previous version.

The client connection retries were removed as they should no longer be necessary - the server is supposed to allow the TCP connection, and then pause communication until the user clicks accept. But I guess it's not doing that... Unfortunately this isn't covered by my unit tests which is probably why I missed it!
