### ISSUE TITLE
Add Vessel:Crew functions

### ISSUE THREAD

**Issue by johnmknight** [krpc/krpc#426]
I'm requesting adding a subset of the existing Crew related methods to the api.
For example:
 GetCrewCapacity ()
 GetCrewCount ()
 GetVesselCrew()

I'm in the process of writing both a new mod to make us of crew information as well as rewriting my old "KSP PAO" mod to use KSP RPC instead of Telemachus.

Cheers!

**Comment by djungelorm** [comment]
I've added Vessel.CrewCapacity, CrewCount and Crew (which returns a list of CrewMember objects) in 2b669e6 Does that cover your needs?
