### ISSUE TITLE
AddStream call fails if procedure ID is used instead of procedure name

### ISSUE THREAD

**Issue by Shimuuar** [krpc/krpc#437]
If one tries to add new stream using procedure ID instead of procedure name call fails with error message `Procedure  not found, in Service SpaceCenter` (note two spaces). If procedure name is used it works normally. I didn't test whether using service ID instead of service name have same effect due to #433.

**Comment by djungelorm** [comment]
Thanks. Just committed a patch that should fix this. Will release it in v0.4.4
