### ISSUE TITLE
KRPC_ERROR_DECODING_FAILED from Arduino

### ISSUE THREAD

**Issue by lkesteloot** [krpc/krpc#446]
The `krpc_connect()` function is returning `KRPC_ERROR_DECODING_FAILED` on my Arduino Uno. The request is getting through because the permission window pops up on KSP with the correct client name. The `krpc_connect()` function returns immediately (not waiting for me to approve on the UI) with that error. The Arduino code then retries (because the error is non-0), and the retry blocks before even sending anything (the TX light doesn't light up).

    do {
      error = krpc_connect(conn, "Arduino Example");
      if (error != KRPC_OK) {
        blink_led(-(int) error);
        delay(100);
      }
    } while (error != KRPC_OK);

I'm running mod version 0.4.4, Arduino library 0.4.4 (from the Arduino Library Manager), on KSP 1.3.1.1891 on Windows 10, over COM3 (USB).

**Comment by djungelorm** [comment]
Looks like this might be due to the client confirmation delay. Under "advanced settings" in the server window, can you try checking "auto-accept new clients" and see if that fixes the issue?

**Comment by djungelorm** [comment]
Yep agreed. I'll see if I can reproduce on a machine that has gdb as would be a lot easier to debug...

**Comment by lkesteloot** [comment]
I don't have dev tools on that machine (it's my son's). If you can't repro on yours, I can install whatever tools are necessary.

**Comment by djungelorm** [comment]
I think I found the issue, and it now works on my Arduino.

I could not reproduce in a POSIX environment, which narrowed it down to the only bit of code that is different on Arduino - the serial connect, read amd write functions. The read function was returning an IO error if no data was available immediately. I've changed it to keep attempting to read data until it receives the expected number of bytes from the server.

**Comment by lkesteloot** [comment]
Yes, `HardwareSerial`'s `readBytes()` returns 0 (or anything less than `count`) if the read times out. Your fix looks good to me.

I notice that you check if `read > count` and return an error. According to the source of `readBytes()` that can never happen, though I'm fine with the check. What's more worrisome is that in that case the buffer would have gotten overrun. So it's a more serious condition than just I/O error. I'm not sure what to suggest as a fix, since it can't happen in principle!

**Comment by djungelorm** [comment]
Ah yes you're right about the excessive check. I was thinking what if the server was misbehaving and sent more data than it should, but this wouldn't catch that.

I'll remove it as it's unnecessary instructions to execute in a very resource restricted environment...
