### ISSUE TITLE
Compatibility with KSP 1.4.0

### ISSUE THREAD

**Issue by duncanj** [krpc/krpc#448]
Since the recent update to 1.4.0, kRPC will no longer load.

**Comment by artwhaley** [comment]
It loaded fine for me and my basic ascent script worked fine on 1.4.0.   Did you get an error message or can you share the log?   

I don't have a build environment set up for it right now to try to compile against 1.4, so there may well be some issues I didn't find, but the 1.3.1 version at least loaded for me.

**Comment by djungelorm** [comment]
v0.4.4 works fine for me to. It does show a warning pop up when the game loads, but it can be safely ignored.

I have also successfully recompiled kRPC v0.4.4 against KSP 1.4 and run the automated test suite. All the tests pass - after a few changes for the updates to the jet engine parameters and other minor things. Also, some of the functionality that the kRPC Drawing service uses have been deprecated by the Unity update, but they still work in KSP 1.4.

I plan to release an updated version of the mod some time this week, which will stop the warning popup appearing, and also include a few other bug fixes (unrelated to the KSP 1.4 update).

**Comment by duncanj** [comment]
Ah. Like a proper fool, I took the start-up error message at face value, without actually testing whether it really worked - sincere apologies! I guess KSP must report mods as being incompatible by default unless they explicitly list that version as compatible?

**Comment by djungelorm** [comment]
That pop up is actually displayed by kRPC, using a bit of code called "CompatibilityChecker" from the forums: https://forum.kerbalspaceprogram.com/index.php?/topic/59388-compatibilitychecker-discussion-thread/
I'd not looked at that thread for a while as the code has always worked, but ferram4 (the author of it) seems to think its unnecessary these days, so maybe I should remove it from kRPC and just rely on version checking elsewhere (like CKAN or the version compatibility reported on the various download sites)

**Comment by Steve-Fry** [comment]
I have something, but I'm not sure if it is a bug or my understanding.

I am working on a PID hover script in python and `vessel.flight().vertical_speed` now always returns 0

In order to get the vertical speed I have to use `vessel.flight(vessel.orbit.body.orbital_reference_frame).vertical_speed`

I am sure this has worked previously?

**Comment by djungelorm** [comment]
That is how it's always been. `vessel.flight` uses a reference frame attached to the vessel by default, so the reported speed will be 0.

**Comment by Steve-Fry** [comment]
> That is how it's always been

🤦‍♂️ 

Thanks for the quick response.

**Comment by duncanj** [comment]
Closing this, as my fears were unfounded and it does genuinely work in 1.4 if you ignore the popup warning.  Thanks all.
