### ISSUE TITLE
kRPC doesn't show up in CKAN

### ISSUE THREAD

**Issue by drafter250** [krpc/krpc#449]
hello thanks for KRPC! was trying to install from latest CKAN 1.24 and Krpc doesn't appear in the mod list.

**Comment by djungelorm** [comment]
Which version of KSP are you using? If it's the new 1.4 then it won't appear as I've not updated its entry in CKAN yet.

**Comment by drafter250** [comment]
yup 1.4

sorry I just got started with mods. So I can uncheck the compatibility filter and it's safe to use?

**Comment by artwhaley** [comment]
I always hate to use words like 'safe' but it works for the rest of us!
According to earlier conversation there may be some data you can't query
about jet engines at the moment?   But just about everything seems to
work!
