### ISSUE TITLE
Python: Transmit Experiment Data

### ISSUE THREAD

**Issue by BurnySc2** [krpc/krpc#456]
Hello, it seems to me there is an issue regarding science data transmission.

The code below tries to run goo-experiments, and after 10 seconds it will try to transmit the data.
The vessel's antenna reports data transmission but after transmission completion, the game science counter only rarely goes up after a transmission (about 5% to 10% of the cases, if I repeat the experiment under exactly the same circumstances).

If I do the transmission manually or using [KOS](https://ksp-kos.github.io/KOS/index.html), it works.

This is my vessel 
[before the script is run](https://i.imgur.com/GgXvyyR.jpg), 
[while the script is run](https://i.imgur.com/a2JaHeo.jpg) and 
[after the script is run](https://i.imgur.com/zdSZNoS.jpg).

```Python
import krpc, time
conn = krpc.connect(name='Science Test')
vessel = conn.space_center.active_vessel
for experiment in vessel.parts.experiments:
    if experiment.part.name == "GooExperiment":
        print("Running experiment on part {}".format(experiment.part.name))
        experiment.run()
        time.sleep(10)
        transmitAmount = sum([x.transmit_value for x in experiment.data])
        print("Transmitting experiment data. Science amount: {}".format(transmitAmount))
        experiment.transmit()
```

**Comment by djungelorm** [comment]
Thanks for spotting this! Should be fixed in the next release.
