### ISSUE TITLE
SpaceCenter::bodies is not available when no ship is loaded

### ISSUE THREAD

**Issue by jazzpi** [krpc/krpc#470]
If I try to call it in the VAB for example, I get

```
terminate called after throwing an instance of 'krpc::RPCError'
  what():  Procedure not available in game scene 'Editor'
```

Is there a reason for this limitation? The mass of Kerbin shouldn't change depending on the vessel you load, right?

**Comment by lucaelin** [comment]
related to #430 i think. There are many other calls in the spacecenter service that should be available without an active vessel, but the current implementation requires the game to be in flight for any call to this service.

**Comment by djungelorm** [comment]
This has been added in v0.4.8. See #471
