### ISSUE TITLE
Symbols not exported when krpc library is compiled in Visual Studio

### ISSUE THREAD

**Issue by nullprofile** [krpc/krpc#474]
Compiling the C++ client library with Visual Studio 2017 results in no .lib being generated. 
Adding `set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)` after line 29 in CMakeLists.txt fixes this. Requires CMake 3.4 or newer.

https://github.com/krpc/krpc/blob/70ff4468db8f2a42dc789b5f9748437e73e13dce/client/cpp/CMakeLists.txt.tmpl#L29-L38

**Comment by djungelorm** [comment]
Thanks for reporting!
