### ISSUE TITLE
Suggestion: Changing interface from Orbit.xxx(Vessel target) to Orbit.xxx(Orbit target)

### ISSUE THREAD

**Issue by haeena** [krpc/krpc#480]
Hi. I'm currently playing KSP with kRPC, that is just great!

My career mode save just reached out of atmosphere of Kerbin, and aiming Minmus for next mission.
Then, I found that some methods in Orbit class only takes Vessel as its argument, e.g. `Orbit.TrueAnomalyAtAN(Vessel target)`.
That seems to work well for rendezvous of vessels, but not well for CelestialBody.

Wondering If we just change interface from Orbit.xxx(Vessel target) to Orbit.xxx(Orbit target), those method should work both for rendezvous of vehicles, moon/interplanetary transfer.

Existing client code need to be changed too, but only a few required.

For instnace, [that code](https://github.com/krpc/krpc-library/blob/master/Art_Whaleys_KRPC_Demos/rendezvous.py#L57
)

```pytnon
ut_an = v.orbit.ut_at_true_anomaly(v.orbit.true_anomaly_an(t))
```

can be simply replaced with this code.

```python
ut_an = v.orbit.ut_at_true_anomaly(v.orbit.true_anomaly_an(t.orbit))
```

If this is acceptable, here's PR for the change. #479

**Comment by djungelorm** [comment]
The PR has been merged and will be a part of the next release. Thanks!
