### ISSUE TITLE
[0.4.6] Drawing.AddDirection() behavior doesn't match documentation

### ISSUE THREAD

**Issue by panourgue** [krpc/krpc#486]
[Quote from documentation](https://krpc.github.io/krpc/csharp/api/drawing/drawing.html#method-KRPC.Client.Services.Drawing.Drawing.AddDirection):
> Draw a direction vector in the scene, **from** the center of mass of the **active vessel**.

Let's try:
```csharp
var conn = new Connection ("Drawing");
var spaceCenter = conn.SpaceCenter ();

var targetRF = spaceCenter.TargetVessel.ReferenceFrame;

conn.Drawing ().AddDirection (
  Tuple.Create (0d, 1d, 0d),      // Up direction
  targetRF,
  2);
);
```
I would expect line **from the CoM of the active vessel**:

![krpc adddirection_expected_s](https://user-images.githubusercontent.com/20702234/43069414-ae011fc0-8e75-11e8-85af-a34cb9bbd846.png)

But [AddDirection() simply draws](https://github.com/krpc/krpc/blob/8ec9007182b56d1aa1f9601af671e5da5840d9f2/service/Drawing/src/Drawing.cs#L45) a vector (argument 1) in the supplied ReferenceFrame (argument 2):

![krpc adddirection_observed_s](https://user-images.githubusercontent.com/20702234/43069445-c117c424-8e75-11e8-9dd1-e2b87ff8959f.png)

To actually get what we want, we have to:

```csharp
var activeRF = spaceCenter.ActiveVessel.ReferenceFrame;

conn.Drawing ().AddDirection (
  spaceCenter.TransformDirection (Tuple.Create (0d, 1d, 0d), targetRF, activeRF),
  activeRF,
  2
);
```

Or, even better:
```csharp
var activeRF = spaceCenter.ActiveVessel.ReferenceFrame;

conn.Drawing ().AddDirection (
  Tuple.Create (0d, 1d, 0d),
  ReferenceFrame.CreateHybrid (conn, activeRF, targetRF),
  2
);
```

P.S. Or am I misunderstanding something?

**Comment by djungelorm** [comment]
This is indeed a bug - thanks for the detailed report! (and sorry for the delay...) Should be an easy fix.
