### ISSUE TITLE
Issues building on Mac

### ISSUE THREAD

**Issue by techdragon** [krpc/krpc#489]
The current Bazel based build is very troublesome on the Mac. None of which seems to be specifically the fault of this plugin's code, more Mono + Mac + Bazel. It's probably a good idea to carefully documenting how to build this on the Mac so others can participate in development. 

I'll try to write something once I actually get it to build :-/

Edit 1 - So far I've had more luck with Jetbrain's Rider IDE than with Bazel, but since it depends on Bazel based dependencies it seems to have some resolution issues with things like KRPC.IO.* and similar parts.

**Comment by djungelorm** [comment]
Hopefully bazel on mac is better now that the year is 2023...
