### ISSUE TITLE
Error on ActiveNextStage.

### ISSUE THREAD

**Issue by pack7df** [krpc/krpc#505]
Hi. When i try to use Baby Sargent engines (As Explorer). When i call ActineNextStage, a random torque appears, a random impulsive torque. After decoupler just continue rotating by inertial. When i do the same with Space bar such random impulsive torque is not present.

I have exactly the same issue with KOS with stage.  
Also i have created some automatic action group in editor like this: when "breaks" the "decouple" and then in kos activate breaks and also the same effect.
I think maybe it's not a problem of KOS or KRPC but some mod is doing something. I'm programmer.; i have donwload KRPC and Kos code and check the code and i can't find the problem. I don;t know what the game does when space bar but i guess is not the same as kos and KRPC. Maybe a problem with physic frame. Please can you give a hint to find the bug?

Thanks.

**Comment by djungelorm** [comment]
Might be a big with KSP itself. Do you get the same issue if you decouple by pressing the space bar? What other mods do you have installed? Try removing them one by one until the issue disappears - that will show which one is causing it if it is a bug in one if your mods.

**Comment by pack7df** [comment]
Thanks for your answer. I solved the problem using InputSimulator Library in order to simulate "space bar" key. Spacebar works perfect but stage by krpc or kos has the same behavior. An impulsive torque appears.

Greetings.

It's a list of my current folders in Gamedata. When i faced the problem i had less.

30/10/2018  02:17    <DIR>          000_AT_Utils
02/10/2018  01:42    <DIR>          000_FilterExtensions
02/10/2018  01:42    <DIR>          000_FilterExtensions_Configs
02/10/2018  01:42    <DIR>          000_TexturesUnlimited
02/10/2018  01:42    <DIR>          000_Toolbar
02/10/2018  01:42    <DIR>          000_TRR_Config
30/10/2018  02:17    <DIR>          000_USITools
01/11/2018  12:30    <DIR>          1745CDB4-InfernalRobotics-LegacyParts-v2.0.0
30/10/2018  06:03    <DIR>          AJE
31/10/2018  10:21    <DIR>          ATK_Propulsion_Pack
02/10/2018  01:42    <DIR>          B9AnimationModules
02/10/2018  01:42    <DIR>          B9PartSwitch
31/10/2018  09:38    <DIR>          B9_Aerospace
02/10/2018  01:42    <DIR>          B9_Aerospace_ProceduralWings
02/10/2018  01:42    <DIR>          BahaSP
02/10/2018  01:42    <DIR>          CommunityCategoryKit
02/10/2018  01:42    <DIR>          CommunityResourcePack
31/10/2018  09:35    <DIR>          CommunityTechTree
02/10/2018  01:42    <DIR>          CommunityTraitIcons
02/10/2018  01:42    <DIR>          ConnectedLivingSpace
02/10/2018  01:42    <DIR>          ContractConfigurator
02/10/2018  01:42    <DIR>          CryoEngines
31/10/2018  10:52    <DIR>          CryoTanks
02/10/2018  01:42    <DIR>          CustomBarnKit
31/10/2018  11:11    <DIR>          DangIt
02/10/2018  01:42    <DIR>          DeadlyReentry
02/10/2018  01:42    <DIR>          DeployableEngines
30/10/2018  05:12    <DIR>          DMagicOrbitalScience
02/10/2018  01:42    <DIR>          DynamicBatteryStorage
02/10/2018  01:42    <DIR>          EngineGroupController
02/10/2018  01:42    <DIR>          FASA
02/10/2018  01:42    <DIR>          FerramAerospaceResearch
02/10/2018  01:42    <DIR>          Firespitter
02/10/2018  01:42    <DIR>          FShangarExtender
31/10/2018  09:39    <DIR>          GroundConstruction
31/10/2018  09:46    <DIR>          HeatControl
02/10/2018  01:42    <DIR>          JanitorsCloset
31/10/2018  11:04    <DIR>          KAS
08/10/2017  04:20    <DIR>          KerbalConstructionTime
31/10/2018  11:09    <DIR>          KerbalFoundries
15/09/2018  01:58    <DIR>          Kerbalism
25/10/2018  04:28    <DIR>          KerbalJointReinforcement
02/10/2018  01:42    <DIR>          KerbalRenamer
31/10/2018  11:13    <DIR>          KIS
02/10/2018  01:42    <DIR>          Kopernicus
30/10/2018  05:24    <DIR>          kOS
09/10/2018  10:56    <DIR>          KRASH
21/10/2018  09:29    <DIR>          kRPC
22/10/2018  02:00    <DIR>          KSCSwitcher
30/11/2018  07:28    <DIR>          KSP-AVC
02/10/2018  01:42    <DIR>          KSPWheel
22/10/2018  02:00    <DIR>          MagiCore
01/11/2018  12:30    <DIR>          MagicSmokeIndustries
12/10/2018  11:28    <DIR>          MechJeb2
02/10/2018  01:42    <DIR>          ModularFlightIntegrator
02/10/2018  01:42    <DIR>          NearFutureConstruction
02/10/2018  01:42    <DIR>          PersistentRotation
02/10/2018  01:42    <DIR>          Principia
02/10/2018  01:42    <DIR>          ProceduralFairings
02/10/2018  01:42    <DIR>          ProceduralParts
02/10/2018  01:42    <DIR>          RCSBuildAid
02/10/2018  01:42    <DIR>          RealChute
02/10/2018  01:42    <DIR>          RealEnginesPack
02/10/2018  01:42    <DIR>          RealFuels
02/10/2018  01:42    <DIR>          RealHeat
09/10/2018  09:02    <DIR>          RealismOverhaul
02/10/2018  01:43    <DIR>          Realistic Heat Managment
02/10/2018  01:43    <DIR>          RealPlume
02/10/2018  01:43    <DIR>          RealScaleBoosters
02/10/2018  01:43    <DIR>          RealSolarSystem
30/10/2018  05:28    <DIR>          RemoteTech
02/10/2018  01:43    <DIR>          REPOSoftTech
02/10/2018  01:43    <DIR>          RetractableLiftingSurface
30/10/2018  05:30    <DIR>          RLA_Stockalike
02/10/2018  01:43    <DIR>          RN_Skylab
02/10/2018  01:43    <DIR>          RN_US_Probes
02/10/2018  01:43    <DIR>          RN_US_Rockets
16/11/2018  10:56    <DIR>          RP-0
02/10/2018  01:43    <DIR>          RSS-Textures
22/10/2018  02:00    <DIR>          RSSDateTime
02/10/2018  01:43    <DIR>          RW Saturatable
30/10/2018  05:32    <DIR>          SCANsat
09/10/2018  10:56    <DIR>          ScrapYard
02/10/2018  01:43    <DIR>          SmokeScreen
02/10/2018  01:43    <DIR>          SolverEngines
02/10/2018  01:44    <DIR>          Squad
15/10/2018  01:21    <DIR>          StageRecovery
01/11/2018  07:09    <DIR>          SXT
02/10/2018  01:44    <DIR>          Taerobee
19/01/2018  11:13    <DIR>          TakeCommand
04/10/2018  11:27    <DIR>          TestFlight
02/10/2018  01:44    <DIR>          TextureReplacerReplaced
02/10/2018  01:44    <DIR>          ThunderAerospace
02/10/2018  01:44    <DIR>          TriggerTech
02/11/2018  07:37    <DIR>          TRP-Hire
02/10/2018  01:44    <DIR>          TweakScale
31/10/2018  11:44    <DIR>          UmbraSpaceIndustries
02/10/2018  01:44    <DIR>          UniversalStorage
19/10/2018  06:11    <DIR>          USI_RO
31/10/2018  11:44    <DIR>          VanguardTechnologies
30/10/2018  05:39    <DIR>          VenStockRevamp
02/10/2018  01:44    <DIR>          [x] Science!

**Comment by djungelorm** [comment]
Closing as most likely a KSP bug, so can't fix.
