### ISSUE TITLE
[question] setPitch value between -1 and 1

### ISSUE THREAD

**Issue by namero999** [krpc/krpc#508]
Hi, I'm building my own custom controller and I have analog joysticks to control orientation and translations. The docs say that I can pass values between -1 and 1 to the set{Pitch/Yaw/Roll} methods. Does that mean that a value of 0.5 for instance (proportional to the joystick position) will make the ship turn more slowly in that direction? Thanks!

**Comment by djungelorm** [comment]
Yep that's exactly how it works.
