### ISSUE TITLE
control does not affect landing legs in even symmetries

### ISSUE THREAD

**Issue by lampeh** [krpc/krpc#509]
I've got an issue with the Python client where vessel.control.legs only works on parts added in odd symmetries (1,3). Legs added in even symmetries (2, 4, 6) are not controlled.

I tested it with nearly-stock (only ModuleManager and kRPC installed). See attached craft and python files.

Is there any more debug info I could provide? Does anyone else see this problem, too?

Could this be related to #261? I noticed that iterating slowly over vessel.parts.legs (allowing enough time to completely retract a leg) would eventually retract all legs, but if I set the deployed attribute of another leg of the same symmetry set to False while the legs are still in motion, the set will actually extend again.

[krpctest1.craft.txt](https://github.com/krpc/krpc/files/2639545/krpctest1.craft.txt)
[krpctest1.py.txt](https://github.com/krpc/krpc/files/2639546/krpctest1.py.txt)

**Comment by JoRadiver** [comment]
Yes it's related to #261 
In [This File](https://github.com/krpc/krpc/blob/master/service/SpaceCenter/src/Services/Control.cs) , line 170
```csharp
public bool Legs {
            get { return parts.Legs.All (part => part.Deployed); }
            set {
                foreach (var part in parts.Legs)
                    if (part.Deployable)
                        part.Deployed = value;
            }
}
```
Since every leg is deployed once, and every deploying call deployes all, even nubers will do nothing in the end. Stumbled across the same Issue while building external KSP hardware.
