### ISSUE TITLE
support for golang / golang client build

### ISSUE THREAD

**Issue by tsal** [krpc/krpc#512]
This issue is mainly asking if you're accepting PRs - this should be relatively simple to add to your build scripts and it's something I'd be glad to do.

Needs:
- [ ] protoc plugin (`go get -u github.com/golang/protobuf/protoc-gen-go`)
- [ ] golang client code
- [ ] Bazel scripts
- [ ] go-specific docs

**Comment by tsal** [comment]
and yes - I realize there's a bunch of documentation that needs to go with this, and I'd be including that in any PRs

**Comment by djungelorm** [comment]
I do of course accept pull requests! Been away for a while but now back working on the mod again.

I wouldn't rush to add a golang client though, I have been working on adding gRPC support to the mod, which support golang (and many other languages at the same time).

**Comment by wallforfry** [comment]
Hi @djungelorm ! What about gRPC today ?

**Comment by djungelorm** [comment]
There were recent discussions on moving to gRPC over on discord. Whilst great in theory, it doesn't appear to be feasible in practice. gRPC requires an HTTP/2 implementation, but the one used by the gRPC csharp library doesn't work in Unity.

**Comment by djungelorm** [comment]
There is also a go client being worked on here: https://github.com/nathan-boulestin/krpc/tree/main/client/go

**Comment by djungelorm** [comment]
Closing as I don't plan to work on this.
Would be happy to merge in the go client that nathan-boulestin is working once it's complete though.
