### ISSUE TITLE
SpaceCenter source file not present for java client code

### ISSUE THREAD

**Issue by patrickcrouch** [krpc/krpc#522]
Most of the other source files are present.  If this could be added it would make debug easier.

**Comment by patrickcrouch** [comment]
[](url)

**Comment by djungelorm** [comment]
Sorry it took me so long to get to this. What do you mean by "present"?

(The SpaceCenter source file and other service files are automatically generated when the Java client JAR is built, and they don't contain anything particularly interesting source-code wise. They are just stubs that call into the remote procedure on the server where the logic actually happens.)

**Comment by djungelorm** [comment]
Closing for now. Please reopen with more details (see above comment).
