### ISSUE TITLE
getting from stream vessel.resources_in_decouple_stage

### ISSUE THREAD

**Issue by kpa23** [krpc/krpc#543]
This code makes an exception on latest krpc-0.4.9-106-ga8ed463 (on version 0.4.8 worked well) .
KSP 1.6.1 with RO and RP-1
```
import krpc

conn = krpc.connect(name='Test1')

vessel = conn.space_center.active_vessel
root = vessel.parts.root
stack = [(root, 0)]
stages = []
while stack:
    part, depth = stack.pop()
    if part.engine and not part.engine.can_shutdown:
        if part.parent.stage not in stages:
            stages.append(part.parent.stage)
            print(' ' * depth, part.title)
    for child in part.children:
        stack.append((child, depth + 1))

for st in stages:
    stage_resources = vessel.resources_in_decouple_stage(stage=st, cumulative=False)
    srb_fuel = conn.add_stream(stage_resources.amount, 'PSPC')
    print(' srb_fuel=', srb_fuel())
```
```
C:\Python\Python37\python.exe E:/PycharmProjects/ksp/2.py
           Castor 1
Traceback (most recent call last):
  File "E:/PycharmProjects/ksp/2.py", line 24, in <module>
    print(' srb_fuel=', srb_fuel())
  File "C:\Python\Python37\lib\site-packages\krpc\stream.py", line 50, in __call__
    raise value  # pylint: disable=raising-bad-type
krpc.error.RPCError: Could not load type 'ModuleDecouplerBase' from assembly 'KRPC.SpaceCenter'.
Server stack trace:
  at KRPC.SpaceCenter.Services.Resources.get_PartResources () [0x00000] in <filename unknown>:0 
  at KRPC.SpaceCenter.Services.Resources.Amount (System.String name) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 

Process finished with exit code 1
```

**Comment by kpa23** [comment]
<details>
<br><summary>GameData mods:</summary>
[x] Science!'<br>
000_ClickThroughBlocker<br>
000_TexturesUnlimited<br>
000_Toolbar<br>
000_TRR_Config<br>
001_ToolbarControl<br>
AJE<br>
B9_Aerospace_ProceduralWings<br>
B9PartSwitch<br>
BahaSP<br>
CommunityResourcePack<br>
ConnectedLivingSpace<br>
ContractConfigurator<br>
CustomBarnKit<br>
DeadlyReentry<br>
DMagicOrbitalScience<br>
DMagicScienceAnimate<br>
EngineGroupController<br>
EnvironmentalVisualEnhancements<br>
FerramAerospaceResearch<br>
Firespitter<br>
FShangarExtender<br>
FuseboxContinued<br>
JanitorsCloset<br>
KerbalEngineer<br>
KerbalJointReinforcement<br>
Kopernicus<br>
kOS<br>
KRASH<br>
kRPC<br>
KSCSwitcher<br>
KSP-AVC<br>
MagiCore<br>
MechJeb2<br>
ModularFlightIntegrator<br>
ModuleManager.4.0.3.dll* <br>
PatchManager<br>
ProceduralFairings<br>
ProceduralFairings-ForEverything<br>
ProceduralParts<br>
RCSBuildAid<br>
RealChute<br>
RealFuels<br>
RealHeat<br>
RealismOverhaul<br>
RealPlume<br>
RealSolarSystem<br>
RemoteTech<br>
REPOSoftTech<br>
ReStock<br>
RetractableLiftingSurface<br>
RN_Solar_Panels<br>
ROCapsules<br>
ROEngines<br>
RP-0<br>
RSS-Textures<br>
RSSVE<br>
SaturableRW<br>
SCANsat<br>
scatterer<br>
ScienceAlert<br>
ShipManifest<br>
SituationModuleInfo<br>
SmokeScreen<br>
SolverEngines<br>
SovietEngines<br>
Squad<br>
StageRecovery<br>
SXT<br>
TextureReplacer<br>
ThunderAerospace<br>
TriggerTech<br>
unBlur.0.5.0.dll*<br>
VenStockRevamp<br>

</details>

**Comment by djungelorm** [comment]
I've managed to reproduce the issue (without mods). Looks like the class `ModuleDecoupler` base was added in KSP 1.7.x, so when kRPC is built against the latest version of KSP and then run in older version of KSP the class is not found when calling methods that need this class.

I'm not sure how to solve this, other than providing a specific build against older versions of KSP.

**Comment by djungelorm** [comment]
Actually I managed to fix this using reflection :D
