### ISSUE TITLE
Specific_impulse returns 0 when throttle is 0

### ISSUE THREAD

**Issue by kpa23** [krpc/krpc#548]
Specific_impulse returns 0 when throttle is 0, but Vacuum and sea_level impulses return non-zero values.
How to reproduce: 

1. Turn engines on to make them active
2. Put throttle to 0

```
import krpc

conn = krpc.connect(name='Test1')

vessel = conn.space_center.active_vessel
print(vessel.specific_impulse, vessel.vacuum_specific_impulse, vessel.kerbin_sea_level_specific_impulse)
```

> 0.0 311.8999938964844 208.50001525878906
> 
> Process finished with exit code 0

**Comment by djungelorm** [comment]
Thanks for reporting.

I tried this with the AeroEquus and it works as expected (in both v0.4.8 and the latest development build). Steps were:
 * Started a new sandbox game
 * Loaded up the AeroEquus onto the launchpad
 * Activated the single liquid fuel engine at the bottom of the stack using right click menu (throlle was already at zero)
 * Ran the above code and got `(250.6501922607422, 320.0, 250.0)`

Are you able to reproduce the bug from a new save, and if so, what steps did you take to do so?
What craft were you using when you got this issue? Maybe send me the craft file so I can try and reproduce?

**Comment by kpa23** [comment]
```
import krpc
import time

conn = krpc.connect(name='Test Spec.Imp. RO mods. RO Engine and RO Fuel')
vessel = conn.space_center.active_vessel
print("No active engines: all zero:")
print(vessel.specific_impulse, vessel.vacuum_specific_impulse, vessel.kerbin_sea_level_specific_impulse)
vessel.control.throttle = 1.0
vessel.control.activate_next_stage()
time.sleep(1)
print("Active engines: all non-zero:")
print(vessel.specific_impulse, vessel.vacuum_specific_impulse, vessel.kerbin_sea_level_specific_impulse)
vessel.control.throttle = 0.0
time.sleep(1)
print("Throttle 0 - specific_impulse is zero, others non-zero:")
print(vessel.specific_impulse, vessel.vacuum_specific_impulse, vessel.kerbin_sea_level_specific_impulse)
```
[TestRocket1.zip](https://github.com/krpc/krpc/files/3648460/TestRocket1.zip)

**Comment by djungelorm** [comment]
Thanks for the detailed info!
