### ISSUE TITLE
Fairings doesn't jettison.

### ISSUE THREAD

**Issue by kpa23** [krpc/krpc#549]
ksp 1.6.1 + RO
Strange behaviour with fairings. They all have jettisoned flag set to True. and .jettison() method doesn't work. In-game clicking on "Jettison fairing" works ok.

[TestRocket1.zip](https://github.com/krpc/krpc/files/3649661/TestRocket1.zip)
```
import krpc

conn = krpc.connect(name='Test Fairings. RO mods')
vessel = conn.space_center.active_vessel
for _ in range(2):
    fairings = [part for part in vessel.parts.with_tag('deployFairing')]
    for fairing in fairings:
        try:
            print("Fairings ", fairing.fairing.part.name, fairing.fairing.jettisoned)
            fairing.fairing.jettison()
        except:
            print("Error")
```

**Comment by djungelorm** [comment]
This appears to be a compatibility issue with ProceduralFairings. They changed the name of the jettison event from "Jettison" to "Jettison Fairing". I've updated kRPC to work with either event name.

**Comment by cym2018** [comment]
For another language  - For me is Chinese - this stll cannot work.
I guess it use different event name for Chinese.
