### ISSUE TITLE
Remove travis access tokens from source

### ISSUE THREAD

**Issue by xnishd** [krpc/krpc#556]
build bot access keys should not be saved public for security reasons.
(didnt find a proper mail adress to contact you)
85e0cfbe99e35f414f5119f2cc2f1bdad8d56cb6

**Comment by nevercast** [comment]
Once these are removed it would be good to regenerate these tokens because they'll be in git history forever.

**Comment by djungelorm** [comment]
These access keys are encrypted, so are safe to disclose publicly. See here for details: https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml
