### ISSUE TITLE
build for KSP 1.8-1.9

### ISSUE THREAD

**Issue by haeena** [krpc/krpc#565]
Hi,

I managed to build the krpc against KSP version 1.8.0.2686, 1.8.1.2694, and 1.9.0.2781 [^1].
Since those versions of ksp use unity version 2019.2.2f1 and unity separate `UnityEngine.dll` into multiple DLLs, it is required to modify build scripts thus build is incompatible to KSP version under 1.8.

If it's acceptable, I will open a pull request.

I'm not sure it's possible to modify build scripts to support all KSP versions from 1.2.2 to 1.9.0... I'm far from bazel experts. But if it's required, I may try.

[^1]: [branch](https://github.com/haeena/krpc/tree/ksp-1.9) and [build files](https://github.com/haeena/krpc/releases/tag/v0.4.9.1)

Thanks,

**Comment by djungelorm** [comment]
A PR would be great!

And yeah I think we may just have to drop support for older versions of ksp. I don't see a way to support both versions of unity.
