### ISSUE TITLE
Is krpc 0.4.8 compatible with KSP 1.9.1.2788?

### ISSUE THREAD

**Issue by a23s4a** [krpc/krpc#574]
Hello. Is krpc 0.4.8 compatible with the latest KSP? I installed it manually and it seems working but it also seems to make heavy use of the graphics card. The fan is rotating at the maximum when krpc service is started from inside the game.
Or should I better wait for a new version of this mod?

**Comment by PizzaRules668** [comment]
It worked until the game bugged out and did not display anything and crashed

**Comment by djungelorm** [comment]
Closing as old. New release coming soon will support latest KSP
