### ISSUE TITLE
C-nano client directory name differ in Arduino lib. manager

### ISSUE THREAD

**Issue by Genhis** [krpc/krpc#580]
Currently, the C-nano client in github releases uses `krpc_cnano` folder for headers but the one in Arduino Library Manager doesn't. This causes problems for other services which depend on kRPC because the generated code has `#include` statements pointing to this folder, as reported in https://github.com/Genhis/KRPC.MechJeb/issues/11#issuecomment-650730169.

Can the names be unified? Is the original reporter doing something incorrectly?

**Comment by djungelorm** [comment]
Working on this. I'll keep the client on github releases as `krpc_cnano` and update the Arduino library to use the same.
