### ISSUE TITLE
Not built on the Linux (Archlinux) by Release-Guide.md

### ISSUE THREAD

**Issue by safocl** [krpc/krpc#588]
You need to add the `maven` dependency instruction to the Release-Guide.md file.
In the file tools/build-against-all-versions.sh on line 16, instead of `mv lib/ksp lib/ksp-orig` you need to do `if [[ -d lib/ksp ]]; then mv lib/ksp lib/ksp-orig; fi`, otherwise the error from `mv` will be thrown.

but I do get the error `ERROR: /home/safff/git/krpc/doc/BUILD:50:10: Setting up python script sphinx-build failed (Exit 127) py_script-setup-sphinx-build failed: error executing command bazel-out/host/bin/doc/py_script-setup-sphinx-build`
[link to full log](http://ix.io/2CB5)

**Comment by safocl** [comment]
and you need add `load("@bazel_tools//tools/build_defs/repo:maven_rules.bzl", "maven_jar")` to WORKSPACE file.

**Comment by djungelorm** [comment]
That error setting up sphinx build is because you need to install python virtualenv

**Comment by djungelorm** [comment]
I have made the other fixes you suggest

**Comment by safocl** [comment]
> That error setting up sphinx build is because you need to install python virtualenv

ok. I'm will be test.
