### ISSUE TITLE
missing input file '//lib:mono-4.5/*.dll'

### ISSUE THREAD

**Issue by safocl** [krpc/krpc#589]
this errors appears when i start tools/build-against-all-versions.sh.
`krpc/tools/build/mono-4.5/BUILD:10:17: //tools/build/mono-4.5:System.Xml: missing input file '//lib:mono-4.5/System.Xml.dll'
krpc/tools/build/mono-4.5/BUILD:8:17: //tools/build/mono-4.5:System.Runtime: missing input file '//lib:mono-4.5/Facades/System.Runtime.dll'
krpc/tools/build/mono-4.5/BUILD:5:17: //tools/build/mono-4.5:mscorlib: missing input file '//lib:mono-4.5/mscorlib.dll'`
and the like...

but all this files exists in `/usr/lib/mono/4.5/` folder

**Comment by djungelorm** [comment]
Looks like the symlink in lib/mono-4.5 was removed in a recent pull request. I'll readd it.

**Comment by joeftiger** [comment]
Overall it would be nice to have a small text telling us what we need to compile this.
So far bazel, maven and mono is needed.

**Comment by kylewill0725** [comment]
Ubuntu: https://krpc.github.io/krpc/compiling.html
Windows: https://github.com/krpc/krpc/blob/master/WINDOWS_BUILDING.md

**Comment by safocl** [comment]
> Ubuntu: https://krpc.github.io/krpc/compiling.html

I'm make as in this tutorial, but now  the new error:
``--> JAVA_HOME=/usr/lib/jvm/java-11-openjdk bazel build //client/cpp
INFO: Analyzed target //client/cpp:cpp (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/safff/git/krpc/tools/krpctools/BUILD:83:10: Setting up python script krpc-clientgen failed (Exit 2): py_script-setup-krpc-clientgen failed: error executing command bazel-out/host/bin/tools/krpctools/py_script-setup-krpc-clientgen
...
virtualenv: error: unrecognized arguments: --no-site-packages`

I delete this argument in this file, but it is created again.

**Comment by kylewill0725** [comment]
What version of virtualenv do you have?

**Comment by safocl** [comment]
> What version of virtualenv do you have?

`--> pacman -Qs virtualenv`
`local/python-virtualenv 20.0.34-1
    `Virtual Python Environment builder`
`local/python2-virtualenv 20.0.34-1
    Virtual Python Environment builder`

**Comment by safocl** [comment]
i have ArchLinux OS

**Comment by kylewill0725** [comment]
I've been using 18.04 Ubuntu which only supports version 15 of python3-virtualenv. See [here](https://stackoverflow.com/a/60783839) why version 20 does not work. I believe the line here: https://github.com/krpc/krpc/blob/46d59f44c21451b3d331378c0da51c28cc8d04a1/tools/build/python.bzl#L18 is where `--site-packages` comes from.

**Comment by safocl** [comment]
> I've been using 18.04 Ubuntu which only supports version 15 of python3-virtualenv. See [here](https://stackoverflow.com/a/60783839) why version 20 does not work. I believe the line here:
> 
> https://github.com/krpc/krpc/blob/46d59f44c21451b3d331378c0da51c28cc8d04a1/tools/build/python.bzl#L18
> is where `--site-packages` comes from.

i remove this arg, but now the new [error](http://ix.io/2CPA)

**Comment by safocl** [comment]
python is not well the programing language -- it is not compatible with old code.

**Comment by djungelorm** [comment]
Looks like this is the main issue in that error log: "ImportError: cannot import name 'Feature' from 'setuptools' "

What version of setuptools are you using?

**Comment by djungelorm** [comment]
Also you shouldn't remove the --no-site-packages flag. It's needed for the build to work properly.

**Comment by safocl** [comment]
> Looks like this is the main issue in that error log: "ImportError: cannot import name 'Feature' from 'setuptools' "
> 
> What version of setuptools are you using?

`local/python-setuptools 1:50.3.0-1`

**Comment by joeftiger** [comment]
Has the original issue been fixed already?

**Comment by safocl** [comment]
> Has the original issue been fixed already?

yes.
