### ISSUE TITLE
ImportError: cannot import name 'Feature' from 'setuptools'

### ISSUE THREAD

**Issue by safocl** [krpc/krpc#590]
i'm have `Archlinux OS`, `python-setuptools 1:50.3.0-1`
this [error](http://ix.io/2CPA) for `PATH=/home/safff/.local/bin:$PATH JAVA_HOME=/usr/lib/jvm/java-11-openjdk bazel build //client/cpp` command.

in this error output is the main:
`ImportError: cannot import name 'Feature' from 'setuptools' (/home/safff/.cache/bazel/_bazel_safff/92df40008d90791a1ad5c088c165ba15/sandbox/linux-sandbox/14/execroot/krpc/bazel-out/host/bin/tools/krpctools/py_script-env-krpc-clientgen.tmp-create-py-env.2/lib/python3.8/site-packages/setuptools/__init__.py)`

**Comment by djungelorm** [comment]
Working on an update that will include upgrading of setuptools. Hopefully will fix the issue, but I don't use arch so can't test.
