### ISSUE TITLE
SASMode don't work

### ISSUE THREAD

**Issue by Zoeille** [krpc/krpc#593]
Like i said in the title, SASMode don't work even if the SAS is on and the Get SASMode return the prograde but in game it didn't put it in retrograde, no error in console or in my app

I use the java api
![image](https://user-images.githubusercontent.com/7293238/101106989-9c33a780-35d1-11eb-9104-8f50a23771bf.png)
![image](https://user-images.githubusercontent.com/7293238/101107006-a81f6980-35d1-11eb-956c-20a5da3556ab.png)

**Comment by kylewill0725** [comment]
What version of KSP and what version of KRPC?

**Comment by jpxthu** [comment]
SAS is not allowed when AutoPilot is enagled:
https://github.com/krpc/krpc/blob/master/service/SpaceCenter/src/Services/AutoPilot.cs#L261

**Comment by Zoeille** [comment]
Yes but even with vessel.getControl() it didn't work at all

**Comment by Zoeille** [comment]
> What version of KSP and what version of KRPC?

I'm using KSP 1.8.1 and 0.4.9-156-g52544abf (as it's write in the VERSION file)

**Comment by Zoeille** [comment]
> SAS is not allowed when `AutoPilot` is enagled:
> https://github.com/krpc/krpc/blob/master/service/SpaceCenter/src/Services/AutoPilot.cs#L261
> 
> `AutoPilot.Disengage()` or set `AutoPilot.TargetDirection` to `-vessel.Velocity`.

Even Target Direction is wrong :( 
![image](https://user-images.githubusercontent.com/7293238/102723762-bd530280-430a-11eb-9635-3db1e7810540.png)

**Comment by Zoeille** [comment]
Fix for retrograde:
```java
vessel.getAutoPilot().setReferenceFrame(refFrame);
                        vessel.getAutoPilot().setTargetDirection(new Triplet<>(0.0,-1.0,0.0));
```
