### ISSUE TITLE
module field value does not update

### ISSUE THREAD

**Issue by DoerteMitHut** [krpc/krpc#606]
When accessing the "Current Angle" field from the "ModuleRoboticRotationServo"-module of the rotoServo.00 part while the servo is moving or after it has moved, the field's returned value stays unchanged until you bring um the right-click menu of the part in-game.

Although I managed to "wiggle" it free and perform some random actions which eventually lead to the field reporting the correct value even during movements, I have not yet found a reliable way to make it work, or eliminate the neccessity for bringing up the right-click menu.

**Comment by djungelorm** [comment]
This is a limitation of KSP and it's PartModule interface.

In 0.5.0 we have added support for robotic parts, which includes workarounds for issues such as these.

Changes in #644
