### ISSUE TITLE
Update Release

### ISSUE THREAD

**Issue by unavaliabl3** [krpc/krpc#610]
The latest binary release of KRPC on GitHub is 0.4.8 from 2018, and it does not work with KSP >= 1.10 well. 
Could maintainers please publish a new binary release of the current master branch?

Thanks

**Comment by lucaelin** [comment]
I am sorry to report that the only maintainer with the required access to publish new builds has gone silent for quite some time now. 
Some forks have managed to created newer builds, check out https://github.com/nullprofile/krpc/releases :)

**Comment by abdullzz** [comment]
newer builds stuck at version 1.21. there's no hope cuz the download speed for that version on steam is unbearable. gonna took you hours

**Comment by artwhaley** [comment]
While the newer build may be compiled against 12.1, it should work with
12.3.
