### ISSUE TITLE
can krpc control multiple ships at the same time?

### ISSUE THREAD

**Issue by submarine1984** [krpc/krpc#620]
can krpc control multiple ships at the same time?
I try to control another rocket by Control.ActivateNextStage() when I control a flighting  plane. Then it will throw an error.
Does it only control the Active vessel?

**Comment by rallen10** [comment]
If someone knows how to do this with kRPC, I would love to know!

**Comment by submarine1984** [comment]
> If someone knows how to do this with kRPC, I would love to know!
I do not read the source code.
But I confirmed after I experiment that it is could to done within 200 meters.
Just make a series of variables representing multiple ships.
But the rocket speed is too fast for the range of 200 meters so I do not know what it can do.

**Comment by djungelorm** [comment]
Yes multiple vessels can be controlled. But they must be within physics range of one another. This is a game limitation we can't avoid.
