### ISSUE TITLE
Support for Windows 10 in Visual Studio 

### ISSUE THREAD

**Issue by GaryDeco** [krpc/krpc#666]
Extend kRPC to support building on Windows OS in Visual Studio .
- [x] Add batch script to copy KSP_x64_Data from default windows location to lib/ 
- [ ] Fix csproj files to use common variable KSP_DIR defined by a  OS check (linux or windows) . 
- [ ] Tweak the windows/visual studio workflow.

**Comment by GaryDeco** [comment]
Issues with .NET 45 targeting. When target is set to .NET 48,  Google Protobuf v 3.10.1 is required for KSP but .NET 48 forces upgrade to v 3.22 (Protobuf). Need to find workaround or solution for targeting .NET45. Environment variables already checked. There could be an issue with where dotnet looks for frameworks vs msbuild?

**Comment by GaryDeco** [comment]
Linking related issues here
-[] #681 
-[] #671

**Comment by djungelorm** [comment]
I did some investigation into how to write a "modern" csproj file in the krpc2 repository. You should take a look at this: https://github.com/krpc/krpc2/blob/main/server/src/KRPC2.csproj

It's so much simpler than the old style. You don't need to specify all the .cs files, it just uses all the ones in the current directory.

I'm also now thinking we don't need that batch file to copy DLLs for various reasons:
 - It's not needed once we can build with Bazel on Windows (which we will have eventually, and will be the preferred approach)
 - All the script wil do is copy a folder into lib/ksp. Just get the user to do it manually! They only have to do it once, so I think this is fine.
 - Not having this script is one less thing we have to maintain (which is a headache if we want it cross platform).

**Comment by GaryDeco** [comment]
That sounds reasonable. No issues on my end.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
