### ISSUE TITLE
Add Pull Request Template to .github/

### ISSUE THREAD

**Issue by GaryDeco** [krpc/krpc#732]
### What would you like to be added?

[PR Template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) overview in GitHbb Docs. 

- Add a PR Template to maintain uniformity and ensure adherence to `Contributions.md` 

### Why is this needed?

- Adding this template will reduce time spent with poorly submitted pull requests and ensure they adhere to `Contributions.md` 
- It is simple to add
- Spend less time debugging and more time adding features. 
__________
Adding @GaryDeco to issue

**Comment by djungelorm** [comment]
Good idea

**Comment by GaryDeco** [comment]
Ok. Removing triage label and I will submit PR
