### ISSUE TITLE
Rewrite the autopilot to use a PID controller

### ISSUE THREAD

**Issue by djungelorm** [krpc/krpc#75]
The autopilot code is currently broken, after the reference frame changes (#66) were merged to master.

It needs to be rewritten, using a PID controller.

**Comment by borogove** [comment]
Autopilot seems a little jerky with lightweight (overtorqued) vessels in 0.1.6, but presumably this issue will address it? Let me know what you learn about PID auto-tuning :)

**Comment by djungelorm** [comment]
Another mod using PID tuning to control attitude: https://github.com/Crzyrndm/Pilot-Assistant

**Comment by so-rose** [comment]
I'm sometimes getting an error that looks like this:
`krpc.error.RPCError: Object reference not set to an instance of an object`
In response to:
```python
#s is my Script library; it instances self.auto.
s.auto.set_direction(node.remaining_burn_vector(), reference_frame=m.vsl().orbital_reference_frame, wait=True)
#m is my Math library; it instances objects as they change.
```

Could this be related in any way?

**Comment by djungelorm** [comment]
That error could be coming from many different places - I'd need a stack trace to know where exactly. Could you please run your code with kRPC configured to output a stack trace with the error, and send me the result? This can be enabled by modifying GameData/kRPC/settings.cfg. Change the line ```verboseErrors = False``` to ```True```.

**Comment by so-rose** [comment]
I recently tried using the `set_direction()` function in another context; it worked. The problem seems to be the node itself, found in my `nodeExec()` function. I'm trying to iterate through all the nodes in the list `control.nodes`, which is when it throws an error. It seems like it could either me me misunderstanding the use of `control.nodes`, or a bug:

```python
def nodeBurn(conn, node) :
    #...
    s.auto.set_direction(node.remaining_burn_vector(), reference_frame = m.vsl().orbital_reference_frame, wait = True)

def nodeExec(conn) :
	#Executes all nodes, in order.
	m = lib.Math(conn)
	l = m.nodeList() #Returns controls.nodes, which should be a list.
	
	for node in range(len(l)) :
		nodeBurn(conn, l[node])

    #The idea is to iterate through every already created node, executing them first to last.
```

I might be able to get a stack trace for you a little later.

It's also worth mentioning my specs:
```
OS: Debian 8 (jessie) on Linux 4.0.0-2-amd64
KSP/Python Version: 1.0.4, 3.4.3
Mod Version: 0.1.10
Python Library Version: 0.1.9 (Latest version according to pip)
```
Finally, any chance you could put up v0.1.10 on pip? :smile: 

Thanks for your time; it's really refreshing to see an active creator!

**Comment by djungelorm** [comment]
Your code looks good. Just off the top of my head (haven't the time to test it right now) it's possible that once a maneuver node is completed (and removed??) the list of nodes changes, hence the null reference exception.

Could maybe try something like:

```python
while len(m.nodeList()) > 0:
    node = m.nodeList()[0]
    nodeBurn(conn, node)
```

I'll have some time on Monday to look into this properly and test it out.

I've added 0.1.10 to pypi. And thanks, I really enjoy working on this mod :)
