### ISSUE TITLE
Pdf

### ISSUE THREAD

**Issue by pavankay** [krpc/krpc#797]
### What would you like to be added?

Could you add a pdf version of the documentation

### Why is this needed?

I was thinking on getting the docs for the python library as a pdf however I cant go to each and every link.

**Comment by djungelorm** [comment]
This already exists. It was supposed to be included in the mod archive, but for some reason it is not. Probably a simple packaging issue. Here's a copy for now, while this gets fixed

[krpc-0.5.4.pdf](https://github.com/user-attachments/files/15810999/krpc-0.5.4.pdf)

**Comment by pavankay** [comment]
Thank you!

**Comment by djungelorm** [comment]
Leaving open to remind me to fix the packaging.

**Comment by pavankay** [comment]
Ok
