### ISSUE TITLE
body mass and gravitational parameter return very wrong values

### ISSUE THREAD

**Issue by Spielopoly** [krpc/krpc#817]
### What happened?

The values returned by vessel.orbit.body.mass and vessel.orbit.body.gravitational_parameter are very wrong by orders of magnitude and sometimes even negative.

### How can someone else reproduce it?

Minimal python script to reproduce error:

```python
import krpc

conn = krpc.connect(name='DEBUG')
vessel = conn.space_center.active_vessel

print(f"Body: {vessel.orbit.body.name}")
print(f"MU: {vessel.orbit.body.gravitational_parameter}")
print(f"Mass: {vessel.orbit.body.mass}")
```

If tested with a rocket somewhere (tested on launchpad, kerbin suborbital flight and on the mun), it gives this output:
Body: Kerbin
MU: 2.646977707734199e-22
Mass: -2.1207643280396482e-11

Body: Mun
MU: 4.3791301452123746e-18
Mass: -3.1153610247081076e-10

The values for a body seem constant even across different save files and game restarts.

### What is your environment?

KSP: v1.12.5
KRPC: v0.5.4

No other mods installed

**Comment by djungelorm** [comment]
Thanks for the bug report. I'll take a look.

**Comment by SurFlurer** [comment]
I got this when I updated krpc server but forgot to update krpc C++ client. After rebuilding with the new client, all is good.
